<?php

use Illuminate\Database\Seeder;

class MstActivityConfigurationTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('mst_activity_configuration')->delete();
        
        \DB::table('mst_activity_configuration')->insert(array (
            0 => 
            array (
                'id' => 5,
                'name' => 'Plate',
                'description' => 'Plate',
                'wbs_id' => 7,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:33:22',
                'updated_at' => '2019-03-06 15:33:22',
            ),
            1 => 
            array (
                'id' => 6,
                'name' => 'Stiffener  Line 1-5',
                'description' => 'Stiffener  Line 1-5',
                'wbs_id' => 7,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:33:31',
                'updated_at' => '2019-03-06 15:33:31',
            ),
            2 => 
            array (
                'id' => 7,
                'name' => 'Stiffener  Line 6',
                'description' => 'Stiffener  Line 6',
                'wbs_id' => 7,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:33:41',
                'updated_at' => '2019-03-06 15:33:41',
            ),
            3 => 
            array (
                'id' => 8,
                'name' => 'Plate',
                'description' => 'Plate',
                'wbs_id' => 8,
                'duration' => 15,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:33:56',
                'updated_at' => '2019-03-06 15:33:56',
            ),
            4 => 
            array (
                'id' => 9,
                'name' => 'H Beam vertikal',
                'description' => 'H Beam vertikal',
                'wbs_id' => 8,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:34:02',
                'updated_at' => '2019-03-06 15:34:02',
            ),
            5 => 
            array (
                'id' => 10,
                'name' => 'Sepatu H-Beam Diagonal',
                'description' => 'Sepatu H-Beam Diagonal',
                'wbs_id' => 8,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:34:07',
                'updated_at' => '2019-03-06 15:34:07',
            ),
            6 => 
            array (
                'id' => 11,
                'name' => 'Plate',
                'description' => 'Plate',
                'wbs_id' => 10,
                'duration' => 16,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:38:01',
                'updated_at' => '2019-03-06 15:38:01',
            ),
            7 => 
            array (
                'id' => 12,
                'name' => 'Stiffener  Line 1-5',
                'description' => 'Stiffener  Line 1-5',
                'wbs_id' => 10,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:38:07',
                'updated_at' => '2019-03-06 15:38:07',
            ),
            8 => 
            array (
                'id' => 13,
                'name' => 'Bracket H Beam',
                'description' => 'Bracket H Beam',
                'wbs_id' => 10,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:38:13',
                'updated_at' => '2019-03-06 15:38:13',
            ),
            9 => 
            array (
                'id' => 14,
                'name' => 'Plate',
                'description' => 'Plate',
                'wbs_id' => 11,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:38:27',
                'updated_at' => '2019-03-06 15:38:27',
            ),
            10 => 
            array (
                'id' => 15,
                'name' => 'Stiffener  Line 1-5',
                'description' => 'Stiffener  Line 1-5',
                'wbs_id' => 11,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:38:32',
                'updated_at' => '2019-03-06 15:38:32',
            ),
            11 => 
            array (
                'id' => 16,
                'name' => 'Stiffener  Line 6',
                'description' => 'Stiffener  Line 6',
                'wbs_id' => 11,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:38:37',
                'updated_at' => '2019-03-06 15:38:37',
            ),
            12 => 
            array (
                'id' => 17,
                'name' => 'Plate',
                'description' => 'Frame 1 - 8/9',
                'wbs_id' => 13,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:41:40',
                'updated_at' => '2019-03-06 15:41:40',
            ),
            13 => 
            array (
                'id' => 18,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 1 - 2',
                'wbs_id' => 13,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:42:01',
                'updated_at' => '2019-03-06 15:42:01',
            ),
            14 => 
            array (
                'id' => 19,
                'name' => 'H Beam Diagonal',
                'description' => 'Frame 2 , 4 , 6 , 8',
                'wbs_id' => 13,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:42:12',
                'updated_at' => '2019-03-06 15:42:12',
            ),
            15 => 
            array (
                'id' => 20,
                'name' => 'Plate',
                'description' => 'Frame 8/9 - 14/15',
                'wbs_id' => 14,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:42:25',
                'updated_at' => '2019-03-06 15:42:25',
            ),
            16 => 
            array (
                'id' => 21,
                'name' => 'Stiffener  Line 4 - 5',
                'description' => 'Frame 8/9 - 9',
                'wbs_id' => 14,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:42:37',
                'updated_at' => '2019-03-06 15:42:37',
            ),
            17 => 
            array (
                'id' => 22,
                'name' => 'Doubling H-Beam',
                'description' => 'Frame 14',
                'wbs_id' => 14,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:42:51',
                'updated_at' => '2019-03-06 15:42:51',
            ),
            18 => 
            array (
                'id' => 23,
                'name' => 'Plate',
                'description' => 'Frame 14/15 - 21/22',
                'wbs_id' => 15,
                'duration' => 15,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:43:08',
                'updated_at' => '2019-03-06 15:43:08',
            ),
            19 => 
            array (
                'id' => 24,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 15 - 17',
                'wbs_id' => 15,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:43:16',
                'updated_at' => '2019-03-06 15:43:16',
            ),
            20 => 
            array (
                'id' => 25,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 17 - 19',
                'wbs_id' => 15,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:43:26',
                'updated_at' => '2019-03-06 15:43:26',
            ),
            21 => 
            array (
                'id' => 26,
                'name' => 'Plate',
                'description' => 'Frame 21/22 - 26',
                'wbs_id' => 16,
                'duration' => 15,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:43:39',
                'updated_at' => '2019-03-06 15:43:39',
            ),
            22 => 
            array (
                'id' => 27,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 21 - 23',
                'wbs_id' => 16,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:43:49',
                'updated_at' => '2019-03-06 15:43:49',
            ),
            23 => 
            array (
                'id' => 28,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 23 - 25',
                'wbs_id' => 16,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:43:59',
                'updated_at' => '2019-03-06 15:43:59',
            ),
            24 => 
            array (
                'id' => 29,
                'name' => 'Plate',
                'description' => 'Frame 29 - 35/36',
                'wbs_id' => 17,
                'duration' => 13,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:44:15',
                'updated_at' => '2019-03-06 15:44:15',
            ),
            25 => 
            array (
                'id' => 30,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 29 - 30',
                'wbs_id' => 17,
                'duration' => 10,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:44:27',
                'updated_at' => '2019-03-06 15:44:27',
            ),
            26 => 
            array (
                'id' => 31,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 30 - 32',
                'wbs_id' => 17,
                'duration' => 10,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:44:37',
                'updated_at' => '2019-03-06 15:44:37',
            ),
            27 => 
            array (
                'id' => 32,
                'name' => 'Plate',
                'description' => 'Frame 35/36 - 42/43',
                'wbs_id' => 18,
                'duration' => 10,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:44:54',
                'updated_at' => '2019-03-06 15:44:54',
            ),
            28 => 
            array (
                'id' => 33,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 36 - 38',
                'wbs_id' => 18,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:45:01',
                'updated_at' => '2019-03-06 15:45:01',
            ),
            29 => 
            array (
                'id' => 34,
                'name' => 'Stiffener  Line 1',
                'description' => 'Frame 38- 39',
                'wbs_id' => 18,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:45:09',
                'updated_at' => '2019-03-06 15:45:09',
            ),
            30 => 
            array (
                'id' => 35,
                'name' => 'Plate',
                'description' => 'Frame 42/43 - 47/48',
                'wbs_id' => 19,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:45:26',
                'updated_at' => '2019-03-06 15:45:26',
            ),
            31 => 
            array (
                'id' => 36,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 42 - 44',
                'wbs_id' => 19,
                'duration' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:45:37',
                'updated_at' => '2019-03-06 15:45:37',
            ),
            32 => 
            array (
                'id' => 37,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 44 - 46',
                'wbs_id' => 19,
                'duration' => 4,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:45:45',
                'updated_at' => '2019-03-06 15:45:45',
            ),
            33 => 
            array (
                'id' => 38,
                'name' => 'Plate',
                'description' => 'Frame 46/47 - 52/53',
                'wbs_id' => 20,
                'duration' => 15,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:46:26',
                'updated_at' => '2019-03-06 15:46:26',
            ),
            34 => 
            array (
                'id' => 39,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 47 - 49',
                'wbs_id' => 20,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:46:38',
                'updated_at' => '2019-03-06 15:46:38',
            ),
            35 => 
            array (
                'id' => 40,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 49 - 51',
                'wbs_id' => 20,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:46:45',
                'updated_at' => '2019-03-06 15:46:45',
            ),
            36 => 
            array (
                'id' => 49,
                'name' => 'Plate',
                'description' => 'Frame 1 - 8/9',
                'wbs_id' => 22,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:50:10',
                'updated_at' => '2019-03-06 15:50:10',
            ),
            37 => 
            array (
                'id' => 50,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 1 - 2',
                'wbs_id' => 22,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:50:20',
                'updated_at' => '2019-03-06 15:50:20',
            ),
            38 => 
            array (
                'id' => 51,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 2 - 4',
                'wbs_id' => 22,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:50:24',
                'updated_at' => '2019-03-06 15:50:24',
            ),
            39 => 
            array (
                'id' => 52,
                'name' => 'Plate',
                'description' => 'Frame 8/9 - 14/15',
                'wbs_id' => 23,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:50:38',
                'updated_at' => '2019-03-06 15:50:38',
            ),
            40 => 
            array (
                'id' => 53,
                'name' => 'Stiffener  Line 1',
                'description' => 'Frame 8/9 - 9',
                'wbs_id' => 23,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:50:51',
                'updated_at' => '2019-03-06 15:50:51',
            ),
            41 => 
            array (
                'id' => 54,
                'name' => 'Stiffener  Line 2',
                'description' => 'Frame 8/9 - 9',
                'wbs_id' => 23,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:50:59',
                'updated_at' => '2019-03-06 15:50:59',
            ),
            42 => 
            array (
                'id' => 55,
                'name' => 'Plate',
                'description' => 'Frame 14/15 - 21/22',
                'wbs_id' => 24,
                'duration' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:51:14',
                'updated_at' => '2019-03-06 15:51:14',
            ),
            43 => 
            array (
                'id' => 56,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 15 - 17',
                'wbs_id' => 24,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:51:23',
                'updated_at' => '2019-03-06 15:51:23',
            ),
            44 => 
            array (
                'id' => 57,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 17 - 19',
                'wbs_id' => 24,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:51:31',
                'updated_at' => '2019-03-06 15:51:31',
            ),
            45 => 
            array (
                'id' => 58,
                'name' => 'Plate',
                'description' => 'Frame 21/22 - 26',
                'wbs_id' => 25,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:51:51',
                'updated_at' => '2019-03-06 15:51:51',
            ),
            46 => 
            array (
                'id' => 59,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 21 - 23',
                'wbs_id' => 25,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:51:58',
                'updated_at' => '2019-03-06 15:51:58',
            ),
            47 => 
            array (
                'id' => 60,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 23 - 25',
                'wbs_id' => 25,
                'duration' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:52:04',
                'updated_at' => '2019-03-06 15:52:04',
            ),
            48 => 
            array (
                'id' => 61,
                'name' => 'Plate',
                'description' => 'Frame 29 - 35/36',
                'wbs_id' => 26,
                'duration' => 10,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:52:21',
                'updated_at' => '2019-03-06 15:52:21',
            ),
            49 => 
            array (
                'id' => 62,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 29 - 30',
                'wbs_id' => 26,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:52:35',
                'updated_at' => '2019-03-06 15:52:35',
            ),
            50 => 
            array (
                'id' => 63,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 30 - 32',
                'wbs_id' => 26,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:52:41',
                'updated_at' => '2019-03-06 15:52:41',
            ),
            51 => 
            array (
                'id' => 64,
                'name' => 'Plate',
                'description' => 'Frame 35/36 - 42/43',
                'wbs_id' => 27,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:52:56',
                'updated_at' => '2019-03-06 15:52:56',
            ),
            52 => 
            array (
                'id' => 65,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 36 - 38',
                'wbs_id' => 27,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:53:29',
                'updated_at' => '2019-03-06 15:53:29',
            ),
            53 => 
            array (
                'id' => 66,
                'name' => 'Stiffener  Line 1',
                'description' => 'Frame 38- 39',
                'wbs_id' => 27,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:53:35',
                'updated_at' => '2019-03-06 15:53:35',
            ),
            54 => 
            array (
                'id' => 67,
                'name' => 'Plate',
                'description' => 'Frame 42/43 - 47/48',
                'wbs_id' => 28,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:53:53',
                'updated_at' => '2019-03-06 15:53:53',
            ),
            55 => 
            array (
                'id' => 68,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 42 - 44',
                'wbs_id' => 28,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:54:02',
                'updated_at' => '2019-03-06 15:54:02',
            ),
            56 => 
            array (
                'id' => 69,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 44 - 46',
                'wbs_id' => 28,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:54:06',
                'updated_at' => '2019-03-06 15:54:06',
            ),
            57 => 
            array (
                'id' => 70,
                'name' => 'Plate',
                'description' => 'Frame 46/47 - 52/53',
                'wbs_id' => 29,
                'duration' => 10,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:54:27',
                'updated_at' => '2019-03-06 15:54:27',
            ),
            58 => 
            array (
                'id' => 71,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 47 - 49',
                'wbs_id' => 29,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:54:35',
                'updated_at' => '2019-03-06 15:54:35',
            ),
            59 => 
            array (
                'id' => 72,
                'name' => 'Stiffener  Line 1 - 5',
                'description' => 'Frame 49 - 51',
                'wbs_id' => 29,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:54:41',
                'updated_at' => '2019-03-06 15:54:41',
            ),
            60 => 
            array (
                'id' => 73,
                'name' => 'Pipa',
                'description' => 'Skeg SB',
                'wbs_id' => 31,
                'duration' => 15,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:57:07',
                'updated_at' => '2019-03-06 15:57:07',
            ),
            61 => 
            array (
                'id' => 74,
                'name' => 'Plate',
                'description' => 'Skeg SB',
                'wbs_id' => 31,
                'duration' => 15,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:57:15',
                'updated_at' => '2019-03-06 15:57:15',
            ),
            62 => 
            array (
                'id' => 75,
                'name' => 'Plate Side Shell',
                'description' => 'Frame 9/10 - 12',
                'wbs_id' => 32,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:57:30',
                'updated_at' => '2019-03-06 15:57:30',
            ),
            63 => 
            array (
                'id' => 76,
                'name' => 'Crop Web Frame',
                'description' => 'Frame 10',
                'wbs_id' => 33,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:57:42',
                'updated_at' => '2019-03-06 15:57:48',
            ),
            64 => 
            array (
                'id' => 77,
                'name' => 'Crop Web Frame',
                'description' => 'Frame 11',
                'wbs_id' => 33,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:57:55',
                'updated_at' => '2019-03-06 15:57:55',
            ),
            65 => 
            array (
                'id' => 78,
                'name' => 'Stiffener  Line 6',
                'description' => 'Frame 9/10 - 12',
                'wbs_id' => 33,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:58:04',
                'updated_at' => '2019-03-06 15:58:04',
            ),
            66 => 
            array (
                'id' => 79,
                'name' => 'Plate Side Shell',
                'description' => 'Frame 19 - 23/24',
                'wbs_id' => 34,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:58:36',
                'updated_at' => '2019-03-06 15:58:36',
            ),
            67 => 
            array (
                'id' => 80,
                'name' => 'Fender Side Shell',
                'description' => 'Frame 19 - 23/24',
                'wbs_id' => 34,
                'duration' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:58:43',
                'updated_at' => '2019-03-06 15:58:43',
            ),
            68 => 
            array (
                'id' => 81,
                'name' => 'Bracket Skat line 6 - 9',
                'description' => 'Frame 19',
                'wbs_id' => 35,
                'duration' => 10,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:59:00',
                'updated_at' => '2019-03-06 15:59:00',
            ),
            69 => 
            array (
                'id' => 82,
                'name' => 'Crop Web Frame Vertikal',
                'description' => 'Frame 20',
                'wbs_id' => 35,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:59:08',
                'updated_at' => '2019-03-06 15:59:08',
            ),
            70 => 
            array (
                'id' => 83,
                'name' => 'Doubling Siku',
                'description' => 'Frame 19 - 23/24',
                'wbs_id' => 35,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:59:14',
                'updated_at' => '2019-03-06 15:59:14',
            ),
            71 => 
            array (
                'id' => 84,
                'name' => 'Plate Side Shell',
                'description' => 'Frame 24 - 27/28',
                'wbs_id' => 36,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:59:53',
                'updated_at' => '2019-03-06 15:59:53',
            ),
            72 => 
            array (
                'id' => 85,
                'name' => 'Stiffener  Line 2',
                'description' => 'Frame 24 - 27/28',
                'wbs_id' => 37,
                'duration' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:00:07',
                'updated_at' => '2019-03-06 16:00:07',
            ),
            73 => 
            array (
                'id' => 86,
                'name' => 'Stiffener  Line 1 & 3',
                'description' => 'Frame 24 - 27/28',
                'wbs_id' => 37,
                'duration' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:00:16',
                'updated_at' => '2019-03-06 16:00:16',
            ),
            74 => 
            array (
                'id' => 87,
                'name' => 'Web Frame',
                'description' => 'Frame 26 , 27',
                'wbs_id' => 37,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:00:21',
                'updated_at' => '2019-03-06 16:00:21',
            ),
            75 => 
            array (
                'id' => 88,
                'name' => 'Plate Bilga',
                'description' => 'Frame 33 - 34',
                'wbs_id' => 38,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:00:35',
                'updated_at' => '2019-03-06 16:00:35',
            ),
            76 => 
            array (
                'id' => 89,
                'name' => 'Plate Side Shell',
                'description' => 'Frame ',
                'wbs_id' => 39,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:00:48',
                'updated_at' => '2019-03-06 16:00:48',
            ),
            77 => 
            array (
                'id' => 90,
                'name' => 'Fender Side Shell',
                'description' => 'Frame ',
                'wbs_id' => 39,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:00:58',
                'updated_at' => '2019-03-06 16:00:58',
            ),
            78 => 
            array (
                'id' => 91,
                'name' => 'Plate Side Shell',
                'description' => 'Frame 50 - 53',
                'wbs_id' => 41,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:01:30',
                'updated_at' => '2019-03-06 16:01:30',
            ),
            79 => 
            array (
                'id' => 92,
                'name' => 'Fender Side Shell',
                'description' => 'Frame 50 - 54',
                'wbs_id' => 41,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:01:38',
                'updated_at' => '2019-03-06 16:01:38',
            ),
            80 => 
            array (
                'id' => 93,
                'name' => 'Web Frame',
                'description' => 'Frame 52/53',
                'wbs_id' => 42,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:01:52',
                'updated_at' => '2019-03-06 16:01:52',
            ),
            81 => 
            array (
                'id' => 94,
                'name' => 'Plate Side Shell',
                'description' => 'Frame 7/8 - 11/12',
                'wbs_id' => 44,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:04:10',
                'updated_at' => '2019-03-06 16:04:10',
            ),
            82 => 
            array (
                'id' => 95,
                'name' => 'Cropping Skat',
                'description' => 'Frame 9',
                'wbs_id' => 45,
                'duration' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:04:23',
                'updated_at' => '2019-03-06 16:04:23',
            ),
            83 => 
            array (
                'id' => 96,
                'name' => 'Stiffener Skat Vertikal',
                'description' => 'Frame 9',
                'wbs_id' => 45,
                'duration' => 9,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:04:32',
                'updated_at' => '2019-03-06 16:04:32',
            ),
            84 => 
            array (
                'id' => 97,
                'name' => 'Bracket Skat',
                'description' => 'Frame 9',
                'wbs_id' => 45,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:04:38',
                'updated_at' => '2019-03-06 16:04:38',
            ),
            85 => 
            array (
                'id' => 98,
                'name' => 'Plate Side Shell',
                'description' => 'Frame 24 - 25/26',
                'wbs_id' => 46,
                'duration' => 15,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:04:50',
                'updated_at' => '2019-03-06 16:04:50',
            ),
            86 => 
            array (
                'id' => 99,
                'name' => 'Crop Web Frame',
                'description' => 'Frame 25',
                'wbs_id' => 47,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:05:01',
                'updated_at' => '2019-03-06 16:05:01',
            ),
            87 => 
            array (
                'id' => 100,
                'name' => 'Stiffener  Line 1 & 3',
                'description' => 'Frame 24 - 25/26',
                'wbs_id' => 47,
                'duration' => 15,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:05:12',
                'updated_at' => '2019-03-06 16:05:12',
            ),
            88 => 
            array (
                'id' => 101,
                'name' => 'Stiffener  Line 2',
                'description' => 'Frame 24 - 25/26',
                'wbs_id' => 47,
                'duration' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:05:23',
                'updated_at' => '2019-03-06 16:05:23',
            ),
            89 => 
            array (
                'id' => 102,
                'name' => 'Plate Side Shell',
                'description' => 'Frame 24 - 27/28',
                'wbs_id' => 48,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:05:32',
                'updated_at' => '2019-03-06 16:05:32',
            ),
            90 => 
            array (
                'id' => 103,
                'name' => 'Crop Web Frame',
                'description' => 'Frame 30',
                'wbs_id' => 49,
                'duration' => 15,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:05:48',
                'updated_at' => '2019-03-06 16:06:02',
            ),
            91 => 
            array (
                'id' => 104,
                'name' => 'Stiffener  Line 1 & 3',
                'description' => 'Frame 27/28 - 29',
                'wbs_id' => 49,
                'duration' => 10,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:05:58',
                'updated_at' => '2019-03-06 16:05:58',
            ),
            92 => 
            array (
                'id' => 105,
                'name' => 'Stiffener  Line 2',
                'description' => 'Frame 27/28 - 29',
                'wbs_id' => 49,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:06:10',
                'updated_at' => '2019-03-06 16:06:10',
            ),
            93 => 
            array (
                'id' => 106,
                'name' => 'Plate Bilga',
                'description' => 'Frame 33 - 34',
                'wbs_id' => 50,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:06:23',
                'updated_at' => '2019-03-06 16:06:23',
            ),
            94 => 
            array (
                'id' => 107,
                'name' => 'Bottom',
                'description' => 'Frame 33 - 34',
                'wbs_id' => 50,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:06:30',
                'updated_at' => '2019-03-06 16:06:30',
            ),
            95 => 
            array (
                'id' => 108,
                'name' => 'Rounbar',
                'description' => '',
                'wbs_id' => 50,
                'duration' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:06:34',
                'updated_at' => '2019-03-06 16:06:34',
            ),
            96 => 
            array (
                'id' => 109,
                'name' => 'Plate Side Shell',
                'description' => 'Frame 35 - 37',
                'wbs_id' => 51,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:06:46',
                'updated_at' => '2019-03-06 16:06:46',
            ),
            97 => 
            array (
                'id' => 110,
                'name' => 'Crop Web Frame',
                'description' => 'Frame 36',
                'wbs_id' => 52,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:06:58',
                'updated_at' => '2019-03-06 16:06:58',
            ),
            98 => 
            array (
                'id' => 111,
                'name' => 'Stiffener  Line 3',
                'description' => 'Frame 35 - 37',
                'wbs_id' => 52,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:07:05',
                'updated_at' => '2019-03-06 16:07:05',
            ),
            99 => 
            array (
                'id' => 112,
                'name' => 'Plate Side Shell',
                'description' => 'Forward ',
                'wbs_id' => 53,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:07:15',
                'updated_at' => '2019-03-06 16:07:15',
            ),
            100 => 
            array (
                'id' => 113,
                'name' => 'Fender Side Shell',
                'description' => 'Forward ',
                'wbs_id' => 53,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:07:24',
                'updated_at' => '2019-03-06 16:07:24',
            ),
            101 => 
            array (
                'id' => 114,
                'name' => 'Plate Side Shell',
                'description' => 'Forward ',
                'wbs_id' => 53,
                'duration' => 10,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:07:32',
                'updated_at' => '2019-03-06 16:07:32',
            ),
            102 => 
            array (
                'id' => 115,
                'name' => 'Plate Side Shell',
                'description' => 'Forward ',
                'wbs_id' => 54,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:07:45',
                'updated_at' => '2019-03-06 16:07:45',
            ),
            103 => 
            array (
                'id' => 116,
                'name' => 'Fender Side Shell',
                'description' => 'Forward ',
                'wbs_id' => 54,
                'duration' => 10,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:07:53',
                'updated_at' => '2019-03-06 16:07:53',
            ),
            104 => 
            array (
                'id' => 117,
                'name' => 'Plate Side Shell',
                'description' => 'Forward ',
                'wbs_id' => 54,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:07:58',
                'updated_at' => '2019-03-06 16:07:58',
            ),
            105 => 
            array (
                'id' => 118,
                'name' => 'Stiffener ',
                'description' => 'Forward ',
                'wbs_id' => 55,
                'duration' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:08:12',
                'updated_at' => '2019-03-06 16:08:12',
            ),
            106 => 
            array (
                'id' => 119,
                'name' => 'Stiffener ',
                'description' => 'Forward ',
                'wbs_id' => 55,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:08:20',
                'updated_at' => '2019-03-06 16:08:20',
            ),
            107 => 
            array (
                'id' => 120,
                'name' => 'Stiffener ',
                'description' => 'Forward ',
                'wbs_id' => 55,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:08:25',
                'updated_at' => '2019-03-06 16:08:25',
            ),
            108 => 
            array (
                'id' => 121,
                'name' => 'Plate Bottom lajur K & A',
                'description' => 'Frame 13 - 18',
                'wbs_id' => 57,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:10:10',
                'updated_at' => '2019-03-06 16:10:10',
            ),
            109 => 
            array (
                'id' => 122,
                'name' => 'Plate Bottom Lajur A & B',
                'description' => 'Frame 19 - 22',
                'wbs_id' => 57,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:10:15',
                'updated_at' => '2019-03-06 16:10:15',
            ),
            110 => 
            array (
                'id' => 123,
                'name' => 'Plate Bottom lajur B',
                'description' => 'Frame 22 - 24',
                'wbs_id' => 57,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:10:21',
                'updated_at' => '2019-03-06 16:10:21',
            ),
            111 => 
            array (
                'id' => 124,
                'name' => 'Plate Bottom lajur C',
                'description' => 'Frame 24 - 28',
                'wbs_id' => 57,
                'duration' => 10,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:10:27',
                'updated_at' => '2019-03-06 16:10:27',
            ),
            112 => 
            array (
                'id' => 125,
                'name' => 'Plate Deck',
                'description' => 'Frame 28 - 29',
                'wbs_id' => 62,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:11:13',
                'updated_at' => '2019-03-06 16:11:13',
            ),
            113 => 
            array (
                'id' => 126,
                'name' => 'Plate Deck Lajur G SB',
                'description' => 'Frame 19/20 - 22/23',
                'wbs_id' => 62,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:11:19',
                'updated_at' => '2019-03-06 16:11:19',
            ),
            114 => 
            array (
                'id' => 127,
                'name' => 'Plate Deck Lajur E SB',
                'description' => 'Plate Deck Lajur E SB',
                'wbs_id' => 62,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:11:24',
                'updated_at' => '2019-03-06 16:11:24',
            ),
            115 => 
            array (
                'id' => 128,
                'name' => 'Inside Plate',
                'description' => 'Inside Plate',
                'wbs_id' => 63,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:11:46',
                'updated_at' => '2019-03-06 16:11:46',
            ),
            116 => 
            array (
                'id' => 129,
                'name' => 'Outside Plate',
                'description' => 'Outside Plate',
                'wbs_id' => 63,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:11:50',
                'updated_at' => '2019-03-06 16:11:50',
            ),
            117 => 
            array (
                'id' => 130,
                'name' => 'Stiffener Frame horizontal',
                'description' => 'Stiffener Frame horizontal',
                'wbs_id' => 63,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:11:56',
                'updated_at' => '2019-03-06 16:11:56',
            ),
            118 => 
            array (
                'id' => 131,
                'name' => 'Plate TOP',
                'description' => 'Plate TOP',
                'wbs_id' => 65,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:12:29',
                'updated_at' => '2019-03-06 16:12:29',
            ),
            119 => 
            array (
                'id' => 132,
                'name' => 'Plate Side',
                'description' => 'Plate Side',
                'wbs_id' => 65,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:12:33',
                'updated_at' => '2019-03-06 16:12:33',
            ),
            120 => 
            array (
                'id' => 133,
                'name' => 'Plate Frame Diagonal',
                'description' => 'Plate Frame Diagonal',
                'wbs_id' => 65,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:12:40',
                'updated_at' => '2019-03-06 16:12:40',
            ),
            121 => 
            array (
                'id' => 134,
                'name' => 'Plate Top',
                'description' => 'Plate Top',
                'wbs_id' => 66,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:13:08',
                'updated_at' => '2019-03-06 16:13:08',
            ),
            122 => 
            array (
                'id' => 135,
                'name' => 'Plate Fwd',
                'description' => 'Plate Fwd',
                'wbs_id' => 66,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:13:12',
                'updated_at' => '2019-03-06 16:13:12',
            ),
            123 => 
            array (
                'id' => 136,
                'name' => 'Plate Side SB & PS',
                'description' => 'Plate Side SB & PS',
                'wbs_id' => 66,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:13:18',
                'updated_at' => '2019-03-06 16:13:18',
            ),
            124 => 
            array (
                'id' => 137,
                'name' => 'Freeing port Plate',
                'description' => 'Freeing port Plate',
                'wbs_id' => 67,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:13:37',
                'updated_at' => '2019-03-06 16:13:37',
            ),
            125 => 
            array (
                'id' => 138,
                'name' => 'Pembuatan Hole freeing port',
                'description' => 'Pembuatan Hole freeing port',
                'wbs_id' => 67,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:13:41',
                'updated_at' => '2019-03-06 16:13:41',
            ),
            126 => 
            array (
                'id' => 139,
                'name' => 'Fabrikasi & Instalasi Freeing port',
                'description' => 'Fabrikasi & Instalasi Freeing port',
                'wbs_id' => 67,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:13:45',
                'updated_at' => '2019-03-06 16:13:45',
            ),
            127 => 
            array (
                'id' => 140,
                'name' => 'Bongkar semen & penyemenan kembali manhole',
                'description' => 'Bongkar semen & penyemenan kembali manhole',
                'wbs_id' => 69,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:15:17',
                'updated_at' => '2019-03-06 16:15:17',
            ),
            128 => 
            array (
                'id' => 141,
                'name' => 'Buta Tutup Man Hole',
                'description' => 'Buta Tutup Man Hole',
                'wbs_id' => 69,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:15:28',
                'updated_at' => '2019-03-06 16:15:28',
            ),
            129 => 
            array (
                'id' => 142,
            'name' => 'Ganti packing karet manhole (material suplai owner)',
            'description' => 'Ganti packing karet manhole (material suplai owner)',
                'wbs_id' => 69,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:15:33',
                'updated_at' => '2019-03-06 16:15:33',
            ),
            130 => 
            array (
                'id' => 143,
                'name' => 'Bongkar & pemasangan baru zink anode',
                'description' => 'Bongkar & pemasangan baru zink anode',
                'wbs_id' => 70,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:15:42',
                'updated_at' => '2019-03-06 16:15:42',
            ),
            131 => 
            array (
                'id' => 144,
                'name' => 'Bongkar Bolder Kn/Ki double Lama',
                'description' => 'Bongkar Bolder Kn/Ki double Lama',
                'wbs_id' => 71,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:15:50',
                'updated_at' => '2019-03-06 16:15:50',
            ),
            132 => 
            array (
                'id' => 145,
                'name' => 'Pemasangan Penambahan Bolder Kn/Ki double baru',
                'description' => 'Pemasangan Penambahan Bolder Kn/Ki double baru',
                'wbs_id' => 71,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:15:54',
                'updated_at' => '2019-03-06 16:15:54',
            ),
            133 => 
            array (
                'id' => 146,
                'name' => 'Pasang Baru Lampu navigasi kn/Ki dan Belakang',
                'description' => 'Pasang Baru Lampu navigasi kn/Ki dan Belakang',
                'wbs_id' => 72,
                'duration' => 2,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:16:06',
                'updated_at' => '2019-03-06 16:16:06',
            ),
            134 => 
            array (
                'id' => 147,
                'name' => 'Bongkar - Pasang Towing Bracket Smit',
                'description' => 'Bongkar - Pasang Towing Bracket Smit',
                'wbs_id' => 73,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:16:17',
                'updated_at' => '2019-03-06 16:16:17',
            ),
            135 => 
            array (
                'id' => 148,
                'name' => 'Pembuatan Baru Towing Bracket Smit',
                'description' => 'Pembuatan Baru Towing Bracket Smit',
                'wbs_id' => 73,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:16:27',
                'updated_at' => '2019-03-06 16:16:27',
            ),
            136 => 
            array (
                'id' => 149,
                'name' => 'Pemasangan wire bridle',
                'description' => 'Pemasangan wire bridle',
                'wbs_id' => 73,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:16:32',
                'updated_at' => '2019-03-06 16:16:32',
            ),
            137 => 
            array (
                'id' => 150,
                'name' => 'Bongkar - Pasang Plimsol Mark " K , I & A , B \'\'',
                'description' => 'Bongkar - Pasang Plimsol Mark " K , I & A , B \'\'',
                'wbs_id' => 74,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:16:42',
                'updated_at' => '2019-03-06 16:16:42',
            ),
            138 => 
            array (
                'id' => 151,
                'name' => 'Pembuatan Baru Plimsol Mark " K , I \'\'',
                'description' => 'Pembuatan Baru Plimsol Mark " K , I \'\'',
                'wbs_id' => 74,
                'duration' => 9,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:16:47',
                'updated_at' => '2019-03-06 16:16:47',
            ),
            139 => 
            array (
                'id' => 152,
                'name' => 'Pembuatan Baru dan Pemasangan Draft  "2= 3 ,  4= 3 , 6= 2 , 8=2 , M= 2 \'\'',
                'description' => 'Pembuatan Baru dan Pemasangan Draft  "2= 3 ,  4= 3 , 6= 2 , 8=2 , M= 2 \'\'',
                'wbs_id' => 74,
                'duration' => 15,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:16:52',
                'updated_at' => '2019-03-06 16:16:52',
            ),
            140 => 
            array (
                'id' => 153,
                'name' => 'Pembuatan Hole Step Ladder',
                'description' => 'Pembuatan Hole Step Ladder',
                'wbs_id' => 75,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:17:00',
                'updated_at' => '2019-03-06 16:17:00',
            ),
            141 => 
            array (
                'id' => 154,
                'name' => 'Penambahan Stiffener di line 6 Hole Step Ladder',
                'description' => 'Penambahan Stiffener di line 6 Hole Step Ladder',
                'wbs_id' => 75,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:17:05',
                'updated_at' => '2019-03-06 16:17:05',
            ),
            142 => 
            array (
                'id' => 155,
                'name' => 'Pembuatan Step Ladder',
                'description' => 'Pembuatan Step Ladder',
                'wbs_id' => 75,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:17:12',
                'updated_at' => '2019-03-06 16:17:12',
            ),
            143 => 
            array (
                'id' => 156,
            'name' => 'Pembuatan Cover Orlop ( Hole Anchor)',
            'description' => 'Pembuatan Cover Orlop ( Hole Anchor)',
                'wbs_id' => 76,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:18:11',
                'updated_at' => '2019-03-06 16:18:11',
            ),
            144 => 
            array (
                'id' => 157,
                'name' => 'Titik 1',
                'description' => 'Titik 1',
                'wbs_id' => 78,
                'duration' => 8,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:18:55',
                'updated_at' => '2019-03-06 16:18:55',
            ),
            145 => 
            array (
                'id' => 158,
                'name' => 'Titik 2',
                'description' => 'Titik 2',
                'wbs_id' => 78,
                'duration' => 10,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:19:00',
                'updated_at' => '2019-03-06 16:19:00',
            ),
            146 => 
            array (
                'id' => 159,
                'name' => 'Titik 3',
                'description' => 'Titik 3',
                'wbs_id' => 78,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:19:04',
                'updated_at' => '2019-03-06 16:19:04',
            ),
            147 => 
            array (
                'id' => 160,
                'name' => 'Lajur 1 ',
                'description' => 'Lajur 1 ',
                'wbs_id' => 80,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:19:36',
                'updated_at' => '2019-03-06 16:19:36',
            ),
            148 => 
            array (
                'id' => 161,
                'name' => 'Lajur 2',
                'description' => 'Lajur 2',
                'wbs_id' => 80,
                'duration' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:19:38',
                'updated_at' => '2019-03-06 16:19:38',
            ),
            149 => 
            array (
                'id' => 162,
                'name' => 'Lajur 3',
                'description' => 'Lajur 3',
                'wbs_id' => 80,
                'duration' => 7,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:19:42',
                'updated_at' => '2019-03-06 16:19:42',
            ),
            150 => 
            array (
                'id' => 163,
                'name' => 'Frame 16 - 17',
                'description' => 'Frame 16 - 17',
                'wbs_id' => 81,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:19:50',
                'updated_at' => '2019-03-06 16:19:50',
            ),
            151 => 
            array (
                'id' => 164,
                'name' => 'Frame 44',
                'description' => 'Frame 44',
                'wbs_id' => 81,
                'duration' => 10,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:19:53',
                'updated_at' => '2019-03-06 16:19:53',
            ),
            152 => 
            array (
                'id' => 165,
                'name' => 'Lajur 1 ',
                'description' => 'Lajur 1 ',
                'wbs_id' => 82,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:20:00',
                'updated_at' => '2019-03-06 16:20:00',
            ),
            153 => 
            array (
                'id' => 166,
                'name' => 'Lajur 2',
                'description' => 'Lajur 2',
                'wbs_id' => 82,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:20:03',
                'updated_at' => '2019-03-06 16:20:03',
            ),
            154 => 
            array (
                'id' => 167,
                'name' => 'Lajur 3',
                'description' => 'Lajur 3',
                'wbs_id' => 82,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:20:07',
                'updated_at' => '2019-03-06 16:20:07',
            ),
            155 => 
            array (
                'id' => 168,
                'name' => 'Frame 11',
                'description' => 'Frame 11',
                'wbs_id' => 83,
                'duration' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:20:15',
                'updated_at' => '2019-03-06 16:20:27',
            ),
            156 => 
            array (
                'id' => 169,
                'name' => 'Frame 16 - 17',
                'description' => 'Frame 16 - 17',
                'wbs_id' => 83,
                'duration' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:20:19',
                'updated_at' => '2019-03-06 16:20:19',
            ),
            157 => 
            array (
                'id' => 170,
                'name' => 'Frame 22',
                'description' => 'Frame 22',
                'wbs_id' => 83,
                'duration' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:20:23',
                'updated_at' => '2019-03-06 16:20:23',
            ),
        ));
        
        
    }
}