<?php

use Illuminate\Database\Seeder;

class MstCustomerTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('mst_customer')->delete();
        
        \DB::table('mst_customer')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'C15001',
                'name' => 'PT PATRIA MARITIME LINES',
                'phone_number_1' => '021-8935016',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl Jababeka XI Blok H30-40',
                'address_2' => 'Kawasan Industri Jababeka, Cikarang',
                'tax_number' => '210511952-431000',
                'pkp_number' => '210511952-431000',
                'email' => NULL,
                'province' => 'Jawa Barat',
                'zip_code' => '17530',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'C15002',
                'name' => 'PT PATRIA MARITIM PERKASA',
                'phone_number_1' => '0778-7367111',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Kav. 20 Dapur 12 Sei Lekop',
                'address_2' => 'Sagulung, Batam',
                'tax_number' => '024597171-217000',
                'pkp_number' => '024597171-217000',
                'email' => NULL,
                'province' => 'Kepulauan Riau',
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'C15003',
                'name' => 'PT PELITA SAMUDERA SHIPPING',
                'phone_number_1' => '021-29308801',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Menara Citicon Lt. 19 Unit A,B & C',
                'address_2' => 'Jl Letjen S Parman Kav. 72 RT 04 RW 003',
                'tax_number' => '025966441-062000',
                'pkp_number' => '025966441-062000',
                'email' => NULL,
                'province' => 'DKI Jakarta',
                'zip_code' => '11410',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'C15004',
                'name' => 'PT MARITIM BARITO PERKASA',
                'phone_number_1' => '0511-4415124',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl.Tembus Pelabuhan Martapura Baru No.25',
                'address_2' => 'RT 26 Mantuil',
                'tax_number' => '023618440-731000',
                'pkp_number' => '023618440-731000',
                'email' => NULL,
                'province' => 'Kalimantan Selatan',
                'zip_code' => '70245',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'C15005',
                'name' => 'PT MITRABAHTERA SEGARA SEJATI',
                'phone_number_1' => '021-57944755',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Gedung Menara Karya Lt 12 Unit A-H',
                'address_2' => 'Jl H.R Rasuna Said Blok X-5 Kav 1-2, Kuningan Timur/Setiabudi',
                'tax_number' => '016411514-054000',
                'pkp_number' => '016411514-054000',
                'email' => NULL,
                'province' => 'DKI Jakarta',
                'zip_code' => '12950',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'C15006',
                'name' => 'PT HASNUR INTERNASIONAL SHIPPING',
                'phone_number_1' => '021-536 2778',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'GED. OFFICE 8 LT. 7, SCBD, LOT 28 JL. JEND. SUDIRMAN KAV. 52-53',
                'address_2' => 'SENAYAN KEBAYORAN BARU JAKARTA SELATAN DKI JAKARTA 12190',
                'tax_number' => '02.900.072.6·038.000',
                'pkp_number' => '02.900.072.6·038.000',
                'email' => NULL,
                'province' => 'DKI JAKARTA',
                'zip_code' => '12190',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'C15007',
                'name' => 'PT LINTAS SAMUDRA BORNEO LINE',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl AES Nasution No. 147',
                'address_2' => 'RT 18 Banjarmasin',
                'tax_number' => '025316852-731000',
                'pkp_number' => '025316852-731000',
                'email' => NULL,
                'province' => 'Kalimantan Selatan',
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'C15008',
                'name' => 'PT BENGKALIS DAYA SYARIKAT',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl Kayu Putih Lima D No 4',
                'address_2' => 'Kel Pulogadung, Kec Pulogadung',
                'tax_number' => '031987548-003000',
                'pkp_number' => '031987548-003000',
                'email' => NULL,
                'province' => 'DKI Jakarta',
                'zip_code' => '13260',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'C15009',
                'name' => 'PT WHS GLOBAL MANDIRI',
                'phone_number_1' => '021-6281846',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl P. Jayakarta Komp. 85 AC-AB, Mangga Dua Selatan',
                'address_2' => 'Mangga Dua Selatan, Sawah Besar',
                'tax_number' => '025303181-073000',
                'pkp_number' => '025303181-073000',
                'email' => NULL,
                'province' => 'DKI Jakarta',
                'zip_code' => '10730',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'C15010',
                'name' => 'PT ANGGUN MARTIM ESAJAYA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Perkantoran CBD Pluit Blok S No. 2',
                'address_2' => 'Jl Pluit Sel. Raya Penjaringan ',
                'tax_number' => '030400410-041000',
                'pkp_number' => '030400410-041000',
                'email' => NULL,
                'province' => 'DKI Jakarta',
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'C15011',
                'name' => 'PT WASKITA KARYA',
                'phone_number_1' => '021-8515550',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl. MT. Haryono Kav. No. 10 ',
                'address_2' => 'Cawang - Jakarta',
                'tax_number' => '010016145-093000',
                'pkp_number' => '010016145-093000',
                'email' => NULL,
                'province' => 'DKI Jakarta',
                'zip_code' => '13340',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'C15012',
                'name' => 'PT MEGAH MANDIRI SUKSES SEJATI',
                'phone_number_1' => '021-63858931',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl KH Hasyim Ashari 125',
                'address_2' => 'Komp Roxy Mas Blok D3-1 Cideng - Gambir',
                'tax_number' => '024667552-028000',
                'pkp_number' => '024667552-028000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'C15013',
                'name' => 'PT INTAN MUSTIKA PAHALA',
                'phone_number_1' => '0511-3275193',
                'phone_number_2' => NULL,
                'contact_name' => 'Endang Jauhari',
                'address_1' => 'Jl. Kayu Putih Lima D No 4',
                'address_2' => 'Kel. Pulogadung, Kec. Pulogadung Jakarta Timur 13260 DKI Jakarta - Indonesia',
                'tax_number' => '032428625-731000',
                'pkp_number' => '032428625-731000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'C15014',
                'name' => 'PT HABCO PRIMATAMA',
                'phone_number_1' => '0761-34302',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl H. Imam Munandar No. 247 FG',
                'address_2' => 'Pekanbaru ',
                'tax_number' => '015546690-218000',
                'pkp_number' => '015546690-218000',
                'email' => NULL,
                'province' => 'Kepulauan Riau',
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'C15015',
                'name' => 'PT UNITED TRACTORS PANDU ENGINEERING',
                'phone_number_1' => '021-8935016',
                'phone_number_2' => NULL,
                'contact_name' => 'Yudistira ',
                'address_1' => 'Jl. Jababeka XI Blok H 30-40 Kawasan Industri Jababeka',
                'address_2' => 'Desa Harjamekar, Kec. Cikarang Utara 17530',
                'tax_number' => '010606028-007000',
                'pkp_number' => '010606028-007000',
                'email' => NULL,
                'province' => 'Jawa Barat',
                'zip_code' => '17530',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'C15016',
                'name' => 'PT TRI SUKSES WANATAMA',
                'phone_number_1' => '021-632 2680',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl AM Sangaji No 11 L-M',
                'address_2' => 'Rw.007 Petojo Utara Gambir - Jakarta Pusat',
                'tax_number' => '018497180-029000',
                'pkp_number' => '018497180-029000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'C15017',
                'name' => 'PT DUTABAHARI MENARA LINE DOCKYARD',
                'phone_number_1' => '0511-4113305',
                'phone_number_2' => NULL,
                'contact_name' => 'Budiman Susandi',
                'address_1' => 'Jl KP Tendean No 174',
                'address_2' => 'RT 17 Gedang, Banjarmasin Tengah',
                'tax_number' => '026138412-731000',
                'pkp_number' => '026138412-731000',
                'email' => NULL,
                'province' => 'Kalimantan Selatan',
                'zip_code' => '70129',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'C15020',
                'name' => 'PT CITA BANGUN NUSANTARA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Komp. Pondok Sejahtera Blok B. No. 9',
                'address_2' => 'Kec. Landasan Ulin – Banjarbaru',
                'tax_number' => NULL,
                'pkp_number' => NULL,
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'C15022',
                'name' => 'PT BINA USAHA MARITIM INDONESIA',
                'phone_number_1' => '021-3806902',
                'phone_number_2' => NULL,
                'contact_name' => 'Marselo ',
                'address_1' => 'Jl Majapahit No 28 C-D',
                'address_2' => 'Petojo Selatan - Gambir',
                'tax_number' => '018562926-028000',
                'pkp_number' => '018562926-028000',
                'email' => NULL,
                'province' => 'DKI Jakarta',
                'zip_code' => '10160',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'C15023',
                'name' => 'PT TANKER ARMADA NUSANTARA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'JL.Pluit Selatan  Raya Blok C No.76-77',
                'address_2' => 'Penjaringan Jakarta - Utara',
                'tax_number' => '018370791-046000',
                'pkp_number' => '018370791-046000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'C15024',
                'name' => 'PT PELAYARAN KARTIKASAMUDRA ADIJAYA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl. Jelawat No. 23 RT.02 RW.01',
                'address_2' => 'Sidomulyo, Samarinda Ilir - Samarinda',
                'tax_number' => '016148959-725000',
                'pkp_number' => '016148959-725000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'C15025',
                'name' => 'PT CAPUTRA MITRA SEJATI',
                'phone_number_1' => '021-6343913',
                'phone_number_2' => NULL,
                'contact_name' => 'Listiyo Prihantoro',
                'address_1' => 'Jl. KH. Hasyim Ashari No. 2, Petojo Utara ',
                'address_2' => 'Jakarta Pusat',
                'tax_number' => '013156732-073000',
                'pkp_number' => '013156732-073000',
                'email' => NULL,
                'province' => 'DKI Jakart',
                'zip_code' => '10130',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'C15026',
                'name' => 'PT BATU ANUGRAH MINERAL RESOURCES',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Synergy Building, Jl Sutera Barat 17 Alam Sutera Lt. 11 Unit 06 RT/RW',
                'address_2' => 'Kel. Panunggangan Timur, Kec. Pinang ',
                'tax_number' => '021448436-416000',
                'pkp_number' => '021448436-416000',
                'email' => NULL,
                'province' => 'Banten',
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'C15027',
                'name' => 'PT GAHARU GALANGAN INTERNATIONAL',
                'phone_number_1' => '021-5747425',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Menara Batavia Lt. 22, Jln KH Mas Mansyur Kav. 126',
                'address_2' => 'Karet Tengsin, Tanah Abang',
                'tax_number' => '029308491-022000',
                'pkp_number' => '029308491-022000',
                'email' => NULL,
                'province' => 'DKI Jakarta',
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'C15028',
                'name' => 'PT PEL DALAM NEGRI ATRIND MARINA GRAHA',
                'phone_number_1' => '0511-479 0777',
                'phone_number_2' => '479 0780',
                'contact_name' => 'Eddy Rachmanto - Finance Manager',
                'address_1' => 'Graha PMA, Jln. Puyau I No. 1 Sungai Besar, Banjarbaru',
                'address_2' => NULL,
                'tax_number' => '012137725-732000',
                'pkp_number' => '012137725-732000',
                'email' => NULL,
                'province' => 'KALIMANTAN SELATAN',
                'zip_code' => '70714',
                'country' => 'Banjarbaru',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'C15029',
                'name' => 'PT ANDHIKA JAYA PERKASA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl Puyau I No 01 RT 012',
                'address_2' => 'Sungai Besar, Banjarbaru Selatan',
                'tax_number' => '030943534-732000',
                'pkp_number' => '030943534-732000',
                'email' => NULL,
                'province' => 'Kalimantan Selatan',
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'C15030',
                'name' => 'PT PRIMA MULTI ARTHA',
                'phone_number_1' => '5114780563',
                'phone_number_2' => NULL,
                'contact_name' => 'Bunhamin Arifin ',
                'address_1' => 'Synergy Building Sutra Barat 17 Alam Sutra Lantai 11 Unit 06',
                'address_2' => 'Penunggangan Timur, Pinang',
                'tax_number' => '024267676-073000',
                'pkp_number' => '024267676-073000',
                'email' => NULL,
                'province' => 'Banten',
                'zip_code' => '15325',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'C15031',
                'name' => 'PT BATUAH ABADI LINES',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => 'PRAYITNO / AGUS ADI',
                'address_1' => 'JL BELITUNG DARAT NO.88',
                'address_2' => 'RT.019 BELITUNG SELATAN  BANJARMASIN  BARAT BANJARMASIN',
                'tax_number' => '023034093-731000',
                'pkp_number' => '023034093-731000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'C15033',
                'name' => 'PT TRANS BUANA SEJAHTERA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => 'ACOY',
                'address_1' => 'JL. AM. SANGAJI  RAYA NO. 11L-M',
                'address_2' => 'PETOJO UTARA-GAMBIR',
                'tax_number' => '029887759-029000',
                'pkp_number' => '029887759-029000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 'C15034',
                'name' => 'PT PANCARAN SAMUDERA TRANSPORT',
                'phone_number_1' => '+62-21-298385781',
                'phone_number_2' => NULL,
                'contact_name' => 'Bpk. Nugroho',
                'address_1' => 'Menara Satu Sentra Kelapa Gading Lantai 6 Suite 0607',
                'address_2' => 'Jl. Bulevar Kelapa Gading LA 3 No. 1 Jakarta / DKI Jakarta / 14240',
                'tax_number' => '026964676-046000',
                'pkp_number' => '026964676-046000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            30 => 
            array (
                'id' => 31,
                'code' => 'C15035',
                'name' => 'PT ARPENI PRATAMA OCEAN LINE',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'APOL, Jl. Abdul Muis No. 50 Petojo Selatan - Gambir Jakarta Pusat ',
                'address_2' => 'DKI Jakarta Raya - 10160',
                'tax_number' => '010018653-092000',
                'pkp_number' => '010018653-092000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            31 => 
            array (
                'id' => 32,
                'code' => 'C15036',
                'name' => 'PT RIMAU SHIPPING',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'JL. AM SANGAJI NO 11 m RT.009 RW.007 PETOJO UTARA - GAMBIR',
                'address_2' => 'JAKARTA PUSAT - DKI JAKARTA 10130',
                'tax_number' => '314073008-029000',
                'pkp_number' => '314073008-029000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            32 => 
            array (
                'id' => 33,
                'code' => 'C15037',
                'name' => 'PT MERATUS ADVANCE MARITIM',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'GEDUNG WISMA RAHARJA LT.6 ZONA C, Jl. TB.SIMATUPANG KAV.1 RT.008 RW.003',
                'address_2' => 'KEL.CILANDAK TIMUR KEC.PASAR MINGGU, JAKARTA SELATAN DKI JAKARTA',
                'tax_number' => '020920831-016000',
                'pkp_number' => '020920831-016000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            33 => 
            array (
                'id' => 34,
                'code' => 'C15038',
                'name' => 'PT TRANSCOAL PACIFIC Tbk',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Bakrie Tower LT.9 Rasuna Epicentrum - Jl. HR Rasuna Said Karet Kuningan',
                'address_2' => 'Kuningan, Setiabudi - Jakarta Selatan ',
                'tax_number' => '021895073-062000',
                'pkp_number' => '021895073-062000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            34 => 
            array (
                'id' => 35,
                'code' => 'C15039',
                'name' => 'PT BERKAH BANUA ENERGI',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'GD. BAKRIE TOWER LT. 9, JL. HR RASUNA SAID KARET KUNINGAN, SETIABUDI',
                'address_2' => 'JAKARTA SELATAN - DKI JAKARTA',
                'tax_number' => '768358541-011000',
                'pkp_number' => '768358541-011000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            35 => 
            array (
                'id' => 36,
                'code' => 'C15040',
                'name' => 'PT MITRA SWIRE CTM',
                'phone_number_1' => '021-57944766',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Gedung Menara Karya Lt 12 Unit A-H',
                'address_2' => 'Jl H.R Rasuna Said Blok X-5 Kav 1-2, Kuningan Timur/Setiabudi',
                'tax_number' => '028449965-063000',
                'pkp_number' => '028449965-063000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            36 => 
            array (
                'id' => 37,
                'code' => 'C15041',
                'name' => 'PT ENERGY TRANSPORTER INDONESIA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'GD. BAKRIE TOWER LT. 9 RASUNA EPICENTRUM JL. HR. RASUNA SAID KARET KUNINGAN, SETIABUDI',
                'address_2' => 'JAKARTA SELATAN - DKI JAKARTA RAYA',
                'tax_number' => '025456906-062000',
                'pkp_number' => '025456906-062000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            37 => 
            array (
                'id' => 38,
                'code' => 'C15042',
                'name' => 'PT KURNIA TUNGGAL NUGRAHA',
                'phone_number_1' => '0741-22376',
                'phone_number_2' => '085266012388',
                'contact_name' => 'JOHAN',
                'address_1' => 'JL. WR. SUPRATMAN NO. 75',
                'address_2' => 'PASAR JAMBI - JAMBI',
                'tax_number' => '018871780-331000',
                'pkp_number' => '018871780-331000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            38 => 
            array (
                'id' => 39,
                'code' => 'C15044',
                'name' => 'PT PELAYARAN RIMBA MEGAH ARMADA',
                'phone_number_1' => '082157684100 ',
                'phone_number_2' => '0561-732233',
                'contact_name' => 'Bapak Hendri',
                'address_1' => 'JL. TRITURA RT.001 RW.001 TANJUNG HILIR',
                'address_2' => 'PONTIANAK TIMUR - PONTIANAK',
                'tax_number' => '016673220-701000',
                'pkp_number' => '016673220-701000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            39 => 
            array (
                'id' => 40,
                'code' => 'C15045',
                'name' => 'PT TRANS POWER MARINE Tbk',
                'phone_number_1' => '021-5155551',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Gedung Artha Graha, lantai 20, Suite 20-01',
                'address_2' => 'Jl. Jend. Sudirman 52-53, Jakarta 12190',
                'tax_number' => '024357121-054000',
                'pkp_number' => '024357121-054000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            40 => 
            array (
                'id' => 41,
                'code' => 'C15046',
                'name' => 'PT PANCARAN MARITIM TRANSPORTINDO',
                'phone_number_1' => '021-29385782',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Menara Satu Sentra Kelapa Gading Lantai 6 Suite 0607',
                'address_2' => 'Jl. Bulevar Kelapa Gading LA 3 No. 1',
                'tax_number' => '317105013-045000',
                'pkp_number' => '317105013-045000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => '14240',
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            41 => 
            array (
                'id' => 42,
                'code' => 'C15047',
                'name' => 'PT TRIM PANDU EGINEERING',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl. Jababeka XI A Blok K No. 9B, Kawasan Industri Jababeka, cikarang ',
                'address_2' => NULL,
                'tax_number' => NULL,
                'pkp_number' => NULL,
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            42 => 
            array (
                'id' => 43,
                'code' => 'C15048',
                'name' => 'PT VIRGO SAMUDERA JAYA',
            'phone_number_1' => '(0511) 3271088',
                'phone_number_2' => NULL,
                'contact_name' => '811506979',
                'address_1' => 'Jl. Rantauan Darat No.2, Kelayan Sel., Banjarmasin Sel., Kota Banjarmasin, Kalimantan Selatan 70241',
                'address_2' => NULL,
                'tax_number' => NULL,
                'pkp_number' => NULL,
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            43 => 
            array (
                'id' => 44,
                'code' => 'C15049',
                'name' => 'PT HARAPAN BAHTERA INTERNUSA',
                'phone_number_1' => '021 25533098',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Menara Karya Lt. 23 Jl. HR. Rasuna Said Blok X-5, Kav 1-2',
                'address_2' => 'Setia Budi, Jakarta Selatan 12950',
                'tax_number' => '020419768-063000',
                'pkp_number' => '020419768-063000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            44 => 
            array (
                'id' => 45,
                'code' => 'C15050',
                'name' => 'PT TRISAKTI BAHARI MANDIRI',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'JL. GATOT SUBROTO TIMUR I NO 133 RT.035 RW.000',
                'address_2' => 'KEBUN BUNGA- BANJARMASIN TIMUR, BANJARMASIN',
                'tax_number' => '032265514-731000',
                'pkp_number' => '032265514-731000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            45 => 
            array (
                'id' => 46,
                'code' => 'C15051',
                'name' => 'PT PATRIA PERIKANAN LESTARI INDONESIA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl Jababeka XI Kawasan Industri Jababeka H No. 30-40',
                'address_2' => 'Hajar Mekar, Cikarang Utara, Kab. Bekasi Jawa Barat ',
                'tax_number' => '812764793-414000',
                'pkp_number' => '812764793-414000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            46 => 
            array (
                'id' => 47,
                'code' => 'C15053',
                'name' => 'PT PERUSAHAAN PELAYARAN RUSIANTO BERSAUDARA',
                'phone_number_1' => '542441260',
                'phone_number_2' => NULL,
                'contact_name' => 'Abu Hadjar',
                'address_1' => 'Jl. Nahkoda No. 23',
                'address_2' => 'Karang Mumus, Samarinda Kota',
                'tax_number' => '014668388-725000',
                'pkp_number' => '014668388-725000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            47 => 
            array (
                'id' => 48,
                'code' => 'C15054',
                'name' => 'PT SERASI SHIPPING INDONESIA',
                'phone_number_1' => '82213220349',
                'phone_number_2' => NULL,
                'contact_name' => 'BAGUS',
                'address_1' => 'GRHA SERA, JL MITRA SUNTER BOULEVARD KAV.90/C-2',
                'address_2' => 'SUNTER JAYA, TANJUNG PRIOK',
                'tax_number' => '030521165-046000',
                'pkp_number' => '030521165-046000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            48 => 
            array (
                'id' => 49,
                'code' => 'C15055',
                'name' => 'PT PELAYARAN MITRABAHARI SENTOSA',
                'phone_number_1' => '0852-5135-2224',
                'phone_number_2' => NULL,
                'contact_name' => 'Yessy Yolanda',
                'address_1' => 'JL. YOS SUDARSO TRISAKTI KOMP. YUKA NO. 25',
                'address_2' => 'RT/RW 002/001  BASIRIH',
                'tax_number' => '016478620-731000',
                'pkp_number' => '016478620-731000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            49 => 
            array (
                'id' => 50,
                'code' => 'C15056',
                'name' => 'PT PELAYARAN BAHTERA JAYA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'JL. AM SANGAJI NO.9R',
                'address_2' => 'PETOJO UTARA GAMBIR',
                'tax_number' => '316988385-029000',
                'pkp_number' => '316988385-029000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            50 => 
            array (
                'id' => 51,
                'code' => 'C15057',
                'name' => 'PT PULAU SEROJA JAYA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'RUKO MEGA GROSIR  CEMPAKA MAS BLOK H NO. 12 & 14',
                'address_2' => 'SUMUR BATU, SUMUR BATU',
                'tax_number' => '017262320-073000',
                'pkp_number' => NULL,
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            51 => 
            array (
                'id' => 52,
                'code' => 'C15058',
                'name' => 'PT BINA PERTIWI',
                'phone_number_1' => '021-46823539',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'JL. RAYA BEKASI KM 22 RT 001',
                'address_2' => 'CAKUNG BARAT, CAKUNG - JAKARTA TIMUR',
                'tax_number' => NULL,
                'pkp_number' => '013176284-007000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            52 => 
            array (
                'id' => 53,
                'code' => 'C15059',
                'name' => 'PT BORNEO SAMUDRA PERKASA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'PANTAI MENTARI BLOK B-3',
                'address_2' => 'KENJERAN-BULAK SURABAYA',
                'tax_number' => NULL,
                'pkp_number' => '023555733-619000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            53 => 
            array (
                'id' => 54,
                'code' => 'C15060',
                'name' => 'PT JHONLIN MARINE TRANS',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'APARTM PALAZO BLOK A29-31 NO. 5',
                'address_2' => 'JL. BENYAMIN SUEB, KEBON KOSONG, KEMAYORAN',
                'tax_number' => '028320208-073000',
                'pkp_number' => '028320208-073000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            54 => 
            array (
                'id' => 55,
                'code' => 'C15061',
                'name' => 'PT PUTRA PERKASA ABADI',
                'phone_number_1' => '0821 3641 5415',
                'phone_number_2' => NULL,
                'contact_name' => 'AGUNG SUPRIANTO',
                'address_1' => 'Plaza Sentra Lt 15 Jl Jend Sudirman Kav 47 - 48 Jakarta 12930',
                'address_2' => NULL,
                'tax_number' => NULL,
                'pkp_number' => NULL,
                'email' => NULL,
                'province' => 'DKI JAKARTA',
                'zip_code' => '12930',
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            55 => 
            array (
                'id' => 56,
                'code' => 'C15062',
                'name' => 'PT PROPER MULTI EQUINDO',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'PLAZA AMINTA LT.3 SUITE 302 JL. LET JEND TB. SIMATUPANG KAV. 10',
                'address_2' => 'PONDOK PINANG KEBAYORAN LAMA',
                'tax_number' => '030791636-009000',
                'pkp_number' => '030791636-009000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            56 => 
            array (
                'id' => 57,
                'code' => 'C15063',
                'name' => 'PT HIJAUPERTIWI INDAH PLANTATIONS',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'JL TRANS KALIMANTAN KM 3.5 RT 06 ',
                'address_2' => 'ANJIR MAMBULAU BARAT KAPUAS TIMUR KAB.KAPUAS',
                'tax_number' => '016150369-711001',
                'pkp_number' => '016150369-711001',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            57 => 
            array (
                'id' => 58,
                'code' => 'C15064',
                'name' => 'PT PELAYARAN MITRABAHARI SENTOSA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'JL. YOS SUDARSO TRISAKTI KOMP. YUKA NO.25',
                'address_2' => 'RT.002 RW.001 BASIRIH, BANJARMASIN BARAT, BANJARMASIN',
                'tax_number' => '016478620-731000',
                'pkp_number' => '016478620-731000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            58 => 
            array (
                'id' => 59,
                'code' => 'C15065',
                'name' => 'PT CAKRAWALA NUSA BAHARI',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'JL. A YANI KM 12.2 GAMBUT BARAT',
                'address_2' => 'GAMBUT BARAT, GAMBUT',
                'tax_number' => '028234847-732000',
                'pkp_number' => '028234847-732000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            59 => 
            array (
                'id' => 60,
                'code' => 'C15066',
                'name' => 'PT TRIM PANDU ENGINEERING',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'KAWASAN INDUSTRI JABABEKA I, JL. JABABEKA XI A BLOK K NO.9B,',
                'address_2' => ' HARJA MEKAR CIKARANG UTARA, BEKASI, JAWA BARAT.',
                'tax_number' => '313037483-435000',
                'pkp_number' => '313037483-435000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            60 => 
            array (
                'id' => 61,
                'code' => 'C15067',
                'name' => 'PT GEMILANG LESTARI TEKNINDO',
                'phone_number_1' => '2174705974',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'JL REMPOA RAYA NO. 79 RT 003 RW 001',
                'address_2' => 'CEMPAKA PUTIH, CIPUTAT TIMUR',
                'tax_number' => '311566970-411000',
                'pkp_number' => '311566970-411000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            61 => 
            array (
                'id' => 62,
                'code' => 'C15068',
                'name' => 'PT NEO ARTHA PRATAMA',
                'phone_number_1' => '021-28512510',
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl. Raya Pulo Ribung PPI BB 46 A No. 07',
                'address_2' => 'Kel. Pekayon Jaya, Kec. Bekasi Selatan, Kota Bekasi.',
                'tax_number' => '701329765-432000',
                'pkp_number' => '701329765-432000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            62 => 
            array (
                'id' => 63,
                'code' => 'C15069',
                'name' => 'PT PELAYARAN FORTUNA NUSANTARA MEGAJAYA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Sudirman Plaza, Plaza Marein Lt. 17 D',
                'address_2' => 'Setiabudi, DKI Jakarta Raya',
                'tax_number' => '018990432-018000',
                'pkp_number' => '018990432-018000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'Indonesia',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            63 => 
            array (
                'id' => 64,
                'code' => 'C15070',
                'name' => 'PT BAHRUL ALAM PERSADA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl. BATU TUMBUH NO.03 RT.003 RW.005 JATI CEMPAKA',
                'address_2' => 'PONDOKGEDE, KOTAMADYA BEKASI, JAWA BARAT',
                'tax_number' => '025045550-432000',
                'pkp_number' => '025045550-432000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            64 => 
            array (
                'id' => 65,
                'code' => 'C15071',
                'name' => 'PT JHONLIN AGRO MANDIRI',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'DS GUNUNG ANTASARI JL KODECO M 1RT.009',
                'address_2' => 'TUNGKARAN PANGERAN - SIMPANG EMPAT TANAH BUMBU - KALIMANTAN SELATAN',
                'tax_number' => '031692197-734000',
                'pkp_number' => '031692197-734000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            65 => 
            array (
                'id' => 66,
                'code' => 'C15072',
                'name' => 'PT JHONLIN BARATAMA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'JL. KODECO KM. 1,5 RT.24, TUNGAKARAN PANGERAN',
                'address_2' => 'TANAH BUMBU, KALIMANTAN SELATAN',
                'tax_number' => '023940257-734000',
                'pkp_number' => '023940257-734000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            66 => 
            array (
                'id' => 67,
                'code' => 'C15073',
                'name' => 'PT FERROUSCO TEKNO INDO',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jln. Raya Inspeksi Kalimalang KM. 23,5/Jln. K. H. Noer Ali No.112',
                'address_2' => 'Desa Cibuntu, Cibitung -  Bekasi',
                'tax_number' => '758630313-435000',
                'pkp_number' => '758630313-435000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            67 => 
            array (
                'id' => 68,
                'code' => 'C15074',
                'name' => 'PT PELAYARAN NASIONAL BINA BUANA RAYA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => 'DINNY',
                'address_1' => NULL,
                'address_2' => NULL,
                'tax_number' => NULL,
                'pkp_number' => NULL,
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            68 => 
            array (
                'id' => 69,
                'code' => 'C15075',
                'name' => 'CV MITRA SURYA TEKNIK',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'Jl. Utan Kalim Rt.004 Rw.006 No. 54 Cimuning',
                'address_2' => 'Mustikajawa, Kota Bekasi, jawa Barat',
                'tax_number' => '211033949432000',
                'pkp_number' => '211033949432000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            69 => 
            array (
                'id' => 70,
                'code' => 'C15076',
                'name' => 'PT IMEDAL KARYA TEKNIK',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'BEKASI TIMUR REGENSI BLOK H7 NO.36 RT.002 RW.015',
                'address_2' => 'CIMUNING, MUSTIKA JAYA, KOTAMADYA BEKASI JAWA BARAT',
                'tax_number' => '314586884-432000',
                'pkp_number' => '314586884-432000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => NULL,
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
            70 => 
            array (
                'id' => 71,
                'code' => 'C15077',
                'name' => 'PT SAFARI SAMUDERA RAYA',
                'phone_number_1' => NULL,
                'phone_number_2' => NULL,
                'contact_name' => NULL,
                'address_1' => 'JL DAHLIA II NO. 19 RT. 034 RW. 000',
                'address_2' => 'TELAWANG-BANJARMASIN BARAT, BANJARMASIN',
                'tax_number' => '024307175-731000',
                'pkp_number' => '024307175-731000',
                'email' => NULL,
                'province' => NULL,
                'zip_code' => NULL,
                'country' => 'INDONESIA',
                'status' => '1',
                'branch_id' => 2,
                'user_id' => NULL,
                'created_at' => '2019-01-19 00:00:00',
                'updated_at' => '2019-01-19 00:00:00',
            ),
        ));
        
        
    }
}