<?php

use Illuminate\Database\Seeder;

class MstWbsConfigurationTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('mst_wbs_configuration')->delete();
        
        \DB::table('mst_wbs_configuration')->insert(array (
            0 => 
            array (
                'id' => 1,
                'number' => 'Docking',
            'description' => 'Docking (Pengedokan)',
                'deliverables' => 'Docking',
                'duration' => 40,
                'wbs_id' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 10:41:34',
                'updated_at' => '2019-04-11 10:41:34',
            ),
            1 => 
            array (
                'id' => 2,
                'number' => 'General Services',
            'description' => 'General Services (Pelayanan Umum)',
                'deliverables' => 'General Services',
                'duration' => 40,
                'wbs_id' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 10:45:37',
                'updated_at' => '2019-04-11 10:45:37',
            ),
            2 => 
            array (
                'id' => 3,
                'number' => 'Working',
                'description' => 'Working ',
                'deliverables' => 'Working ',
                'duration' => 40,
                'wbs_id' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 10:55:39',
                'updated_at' => '2019-04-11 10:55:39',
            ),
            3 => 
            array (
                'id' => 4,
                'number' => 'Blasting & Coating',
                'description' => 'Blasting & Coating',
                'deliverables' => 'Blasting & Coating',
                'duration' => 10,
                'wbs_id' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 10:55:58',
                'updated_at' => '2019-04-11 10:55:58',
            ),
            4 => 
            array (
                'id' => 5,
                'number' => 'Replating',
            'description' => 'Penggantian Plat (Replating)',
                'deliverables' => 'Replating',
                'duration' => 60,
                'wbs_id' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:31:16',
                'updated_at' => '2019-03-06 15:32:02',
            ),
            5 => 
            array (
                'id' => 6,
                'number' => 'Sideboard Forward',
                'description' => 'Sideboard Forward',
                'deliverables' => 'Sideboard Forward',
                'duration' => 55,
                'wbs_id' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:32:44',
                'updated_at' => '2019-03-06 15:32:44',
            ),
            6 => 
            array (
                'id' => 7,
                'number' => 'Panel Block F1 - F2',
                'description' => 'Panel Block F1 - F2',
                'deliverables' => 'Panel Block F1 - F2',
                'duration' => 50,
                'wbs_id' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:32:58',
                'updated_at' => '2019-03-06 15:32:58',
            ),
            7 => 
            array (
                'id' => 8,
                'number' => 'Panel Block F3',
                'description' => 'Panel Block F3',
                'deliverables' => 'Panel Block F3',
                'duration' => 50,
                'wbs_id' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:33:07',
                'updated_at' => '2019-03-06 15:33:07',
            ),
            8 => 
            array (
                'id' => 9,
                'number' => 'Sideboard After',
                'description' => 'Sideboard After',
                'deliverables' => 'Sideboard After',
                'duration' => 35,
                'wbs_id' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:34:31',
                'updated_at' => '2019-03-06 15:34:31',
            ),
            9 => 
            array (
                'id' => 10,
                'number' => 'Panel Block A1 - A2',
                'description' => 'Panel Block A1 - A2',
                'deliverables' => 'Panel Block A1 - A2',
                'duration' => 40,
                'wbs_id' => 9,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:37:26',
                'updated_at' => '2019-03-06 15:37:26',
            ),
            10 => 
            array (
                'id' => 11,
                'number' => 'Panel Block A3 - A4',
                'description' => 'Panel Block A3 - A4',
                'deliverables' => 'Panel Block A3 - A4',
                'duration' => 25,
                'wbs_id' => 9,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:37:35',
                'updated_at' => '2019-03-06 15:37:35',
            ),
            11 => 
            array (
                'id' => 12,
                'number' => 'Sideboard Star Board',
                'description' => 'Sideboard Star Board',
                'deliverables' => 'Sideboard Star Board',
                'duration' => 45,
                'wbs_id' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:38:56',
                'updated_at' => '2019-03-06 15:38:56',
            ),
            12 => 
            array (
                'id' => 13,
                'number' => 'Panel Block P1 - P2',
                'description' => 'Panel Block P1 - P2',
                'deliverables' => 'Panel Block P1 - P2',
                'duration' => 35,
                'wbs_id' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:39:06',
                'updated_at' => '2019-03-06 15:39:06',
            ),
            13 => 
            array (
                'id' => 14,
                'number' => 'Panel Block P3 - P4',
                'description' => 'Panel Block P3 - P4',
                'deliverables' => 'Panel Block P3 - P4',
                'duration' => 22,
                'wbs_id' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:39:13',
                'updated_at' => '2019-03-06 15:39:13',
            ),
            14 => 
            array (
                'id' => 15,
                'number' => 'Panel Block P5 - P6',
                'description' => 'Panel Block P5 - P6',
                'deliverables' => 'Panel Block P5 - P6',
                'duration' => 27,
                'wbs_id' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:39:21',
                'updated_at' => '2019-03-06 15:39:21',
            ),
            15 => 
            array (
                'id' => 16,
                'number' => 'Panel Block P7 - P8',
                'description' => 'Panel Block P7 - P8',
                'deliverables' => 'Panel Block P7 - P8',
                'duration' => 20,
                'wbs_id' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:39:30',
                'updated_at' => '2019-03-06 15:39:30',
            ),
            16 => 
            array (
                'id' => 17,
                'number' => 'Panel Block P9 - P10',
                'description' => 'Panel Block P9 - P10',
                'deliverables' => 'Panel Block P9 - P10',
                'duration' => 30,
                'wbs_id' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:39:39',
                'updated_at' => '2019-03-06 15:39:39',
            ),
            17 => 
            array (
                'id' => 18,
                'number' => 'Panel Block P11 - P12',
                'description' => 'Panel Block P11 - P12',
                'deliverables' => 'Panel Block P11 - P12',
                'duration' => 25,
                'wbs_id' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:39:51',
                'updated_at' => '2019-03-06 15:39:51',
            ),
            18 => 
            array (
                'id' => 19,
                'number' => 'Panel Block P13 - P14',
                'description' => 'Panel Block P13 - P14',
                'deliverables' => 'Panel Block P13 - P14',
                'duration' => 28,
                'wbs_id' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:40:01',
                'updated_at' => '2019-03-06 15:40:01',
            ),
            19 => 
            array (
                'id' => 20,
                'number' => 'Panel Block P15 - P16',
                'description' => 'Panel Block P15 - P16',
                'deliverables' => 'Panel Block P15 - P16',
                'duration' => 32,
                'wbs_id' => 12,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:40:10',
                'updated_at' => '2019-03-06 15:40:10',
            ),
            20 => 
            array (
                'id' => 21,
                'number' => 'Sideboard Portside',
                'description' => 'Sideboard Portside',
                'deliverables' => 'Sideboard Portside',
                'duration' => 40,
                'wbs_id' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:46:58',
                'updated_at' => '2019-03-06 15:46:58',
            ),
            21 => 
            array (
                'id' => 22,
                'number' => 'Panel Block P1 - P2',
                'description' => 'Panel Block P1 - P2',
                'deliverables' => 'Panel Block P1 - P2',
                'duration' => 25,
                'wbs_id' => 21,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:48:59',
                'updated_at' => '2019-03-06 15:48:59',
            ),
            22 => 
            array (
                'id' => 23,
                'number' => 'Panel Block P3 - P4',
                'description' => 'Panel Block P3 - P4',
                'deliverables' => 'Panel Block P3 - P4',
                'duration' => 20,
                'wbs_id' => 21,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:49:06',
                'updated_at' => '2019-03-06 15:49:06',
            ),
            23 => 
            array (
                'id' => 24,
                'number' => 'Panel Block P5 - P6',
                'description' => 'Panel Block P5 - P6',
                'deliverables' => 'Panel Block P5 - P6',
                'duration' => 25,
                'wbs_id' => 21,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:49:12',
                'updated_at' => '2019-03-06 15:49:12',
            ),
            24 => 
            array (
                'id' => 25,
                'number' => 'Panel Block P7 - P8',
                'description' => 'Panel Block P7 - P8',
                'deliverables' => 'Panel Block P7 - P8',
                'duration' => 20,
                'wbs_id' => 21,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:49:19',
                'updated_at' => '2019-03-06 15:49:19',
            ),
            25 => 
            array (
                'id' => 26,
                'number' => 'Panel Block P9 - P10',
                'description' => 'Panel Block P9 - P10',
                'deliverables' => 'Panel Block P9 - P10',
                'duration' => 25,
                'wbs_id' => 21,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:49:25',
                'updated_at' => '2019-03-06 15:49:25',
            ),
            26 => 
            array (
                'id' => 27,
                'number' => 'Panel Block P11 - P12',
                'description' => 'Panel Block P11 - P12',
                'deliverables' => 'Panel Block P11 - P12',
                'duration' => 30,
                'wbs_id' => 21,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:49:37',
                'updated_at' => '2019-03-06 15:49:37',
            ),
            27 => 
            array (
                'id' => 28,
                'number' => 'Panel Block P13 - P14',
                'description' => 'Panel Block P13 - P14',
                'deliverables' => 'Panel Block P13 - P14',
                'duration' => 25,
                'wbs_id' => 21,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:49:43',
                'updated_at' => '2019-03-06 15:49:43',
            ),
            28 => 
            array (
                'id' => 29,
                'number' => 'Panel Block P15 - P16',
                'description' => 'Panel Block P15 - P16',
                'deliverables' => 'Panel Block P15 - P16',
                'duration' => 20,
                'wbs_id' => 21,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:49:51',
                'updated_at' => '2019-03-06 15:49:51',
            ),
            29 => 
            array (
                'id' => 30,
                'number' => 'Replating Star Board',
                'description' => 'Replating Star Board',
                'deliverables' => 'Replating Star Board',
                'duration' => 35,
                'wbs_id' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:55:43',
                'updated_at' => '2019-03-06 15:55:43',
            ),
            30 => 
            array (
                'id' => 31,
                'number' => 'Replating Skeg',
                'description' => 'Replating Skeg',
                'deliverables' => 'Replating Skeg',
                'duration' => 25,
                'wbs_id' => 30,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:55:52',
                'updated_at' => '2019-03-06 15:55:52',
            ),
            31 => 
            array (
                'id' => 32,
                'number' => 'Replating Side Shell Frame 9/10 - 12',
                'description' => 'Replating Side Shell Frame 9/10 - 12',
                'deliverables' => 'Replating Side Shell Frame 9/10 - 12',
                'duration' => 25,
                'wbs_id' => 30,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:55:57',
                'updated_at' => '2019-03-06 15:55:57',
            ),
            32 => 
            array (
                'id' => 33,
                'number' => 'Replating Internal Tank Side Shell Frame 9/10 - 12',
                'description' => 'Replating Internal Tank Side Shell Frame 9/10 - 12',
                'deliverables' => 'Replating Internal Tank Side Shell Frame 9/10 - 12',
                'duration' => 25,
                'wbs_id' => 30,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:56:01',
                'updated_at' => '2019-03-06 15:56:01',
            ),
            33 => 
            array (
                'id' => 34,
                'number' => 'Replating Side Shell Frame 19 - 23/24',
                'description' => 'Replating Side Shell Frame 19 - 23/24',
                'deliverables' => 'Replating Side Shell Frame 19 - 23/24',
                'duration' => 25,
                'wbs_id' => 30,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:56:06',
                'updated_at' => '2019-03-06 15:56:06',
            ),
            34 => 
            array (
                'id' => 35,
                'number' => 'Replating Internal Tank Side Shell Frame 19 - 23/24',
                'description' => 'Replating Internal Tank Side Shell Frame 19 - 23/24',
                'deliverables' => 'Replating Internal Tank Side Shell Frame 19 - 23/24',
                'duration' => 25,
                'wbs_id' => 30,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:56:11',
                'updated_at' => '2019-03-06 15:56:11',
            ),
            35 => 
            array (
                'id' => 36,
                'number' => 'Replating Side Shell Frame 24 - 27/28',
                'description' => 'Replating Side Shell Frame 24 - 27/28',
                'deliverables' => 'Replating Side Shell Frame 24 - 27/28',
                'duration' => 25,
                'wbs_id' => 30,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:56:17',
                'updated_at' => '2019-03-06 15:56:17',
            ),
            36 => 
            array (
                'id' => 37,
                'number' => 'Replating Internal Tank Side Shell Frame 24 - 27/28',
                'description' => 'Replating Internal Tank Side Shell Frame 24 - 27/28',
                'deliverables' => 'Replating Internal Tank Side Shell Frame 24 - 27/28',
                'duration' => 25,
                'wbs_id' => 30,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:56:22',
                'updated_at' => '2019-03-06 15:56:22',
            ),
            37 => 
            array (
                'id' => 38,
                'number' => 'Replating Bilga Frame 26 - 28',
                'description' => 'Replating Bilga Frame 26 - 28',
                'deliverables' => 'Replating Bilga Frame 26 - 28',
                'duration' => 25,
                'wbs_id' => 30,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:56:27',
                'updated_at' => '2019-03-06 15:56:27',
            ),
            38 => 
            array (
                'id' => 39,
                'number' => 'Replating Side Shell Frame 28 - 29',
                'description' => 'Replating Side Shell Frame 28 - 29',
                'deliverables' => 'Replating Side Shell Frame 28 - 29',
                'duration' => 25,
                'wbs_id' => 30,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:56:31',
                'updated_at' => '2019-03-06 15:56:31',
            ),
            39 => 
            array (
                'id' => 40,
                'number' => 'Replating Side Shell Frame 45/46 - 48',
                'description' => 'Replating Side Shell Frame 45/46 - 48',
                'deliverables' => 'Replating Side Shell Frame 45/46 - 48',
                'duration' => 25,
                'wbs_id' => 30,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:56:40',
                'updated_at' => '2019-03-06 15:56:40',
            ),
            40 => 
            array (
                'id' => 41,
                'number' => 'Replating Side Shell Frame 50 - 53',
                'description' => 'Replating Side Shell Frame 50 - 53',
                'deliverables' => 'Replating Side Shell Frame 50 - 53',
                'duration' => 25,
                'wbs_id' => 30,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:56:45',
                'updated_at' => '2019-03-06 15:56:45',
            ),
            41 => 
            array (
                'id' => 42,
                'number' => 'Replating Internal Tank Side Shell Frame 50 - 53',
                'description' => 'Replating Internal Tank Side Shell Frame 50 - 53',
                'deliverables' => 'Replating Internal Tank Side Shell Frame 50 - 53',
                'duration' => 25,
                'wbs_id' => 30,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 15:56:52',
                'updated_at' => '2019-03-06 15:56:52',
            ),
            42 => 
            array (
                'id' => 43,
                'number' => 'Replating Port Side',
                'description' => 'Replating Port Side',
                'deliverables' => 'Replating Port Side',
                'duration' => 40,
                'wbs_id' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:02:08',
                'updated_at' => '2019-03-06 16:02:08',
            ),
            43 => 
            array (
                'id' => 44,
                'number' => 'Replating Side Shell Frame 7/8 - 11/12',
                'description' => 'Replating Side Shell Frame 7/8 - 11/12',
                'deliverables' => 'Replating Side Shell Frame 7/8 - 11/12',
                'duration' => 30,
                'wbs_id' => 43,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:02:18',
                'updated_at' => '2019-03-06 16:02:18',
            ),
            44 => 
            array (
                'id' => 45,
                'number' => 'Replating Internal Tank Side Shell Frame 7/8 - 11/12',
                'description' => 'Replating Internal Tank Side Shell Frame 7/8 - 11/12',
                'deliverables' => 'Replating Internal Tank Side Shell Frame 7/8 - 11/12',
                'duration' => 25,
                'wbs_id' => 43,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:02:24',
                'updated_at' => '2019-03-06 16:02:24',
            ),
            45 => 
            array (
                'id' => 46,
                'number' => 'Replating Side Shell Frame 24 - 25/26',
                'description' => 'Replating Side Shell Frame 24 - 25/26',
                'deliverables' => 'Replating Side Shell Frame 24 - 25/26',
                'duration' => 28,
                'wbs_id' => 43,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:02:30',
                'updated_at' => '2019-03-06 16:02:30',
            ),
            46 => 
            array (
                'id' => 47,
                'number' => 'Replating internal Tank Side Shell Frame 24 - 25/26',
                'description' => 'Replating internal Tank Side Shell Frame 24 - 25/26',
                'deliverables' => 'Replating internal Tank Side Shell Frame 24 - 25/26',
                'duration' => 22,
                'wbs_id' => 43,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:02:38',
                'updated_at' => '2019-03-06 16:02:38',
            ),
            47 => 
            array (
                'id' => 48,
                'number' => 'Replating Side Shell Frame 27/28 - 31',
                'description' => 'Replating Side Shell Frame 27/28 - 31',
                'deliverables' => 'Replating Side Shell Frame 27/28 - 31',
                'duration' => 25,
                'wbs_id' => 43,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:02:42',
                'updated_at' => '2019-03-06 16:02:42',
            ),
            48 => 
            array (
                'id' => 49,
                'number' => 'Replating Internal Tank Side Shell Frame 27/28 - 31',
                'description' => 'Replating Internal Tank Side Shell Frame 27/28 - 31',
                'deliverables' => 'Replating Internal Tank Side Shell Frame 27/28 - 31',
                'duration' => 32,
                'wbs_id' => 43,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:02:49',
                'updated_at' => '2019-03-06 16:02:49',
            ),
            49 => 
            array (
                'id' => 50,
                'number' => 'Replating Bilga Frame 33 - 34',
                'description' => 'Replating Bilga Frame 33 - 34',
                'deliverables' => 'Replating Bilga Frame 33 - 34',
                'duration' => 25,
                'wbs_id' => 43,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:02:58',
                'updated_at' => '2019-03-06 16:02:58',
            ),
            50 => 
            array (
                'id' => 51,
                'number' => 'Replating Side Shell Frame 35 - 37',
                'description' => 'Replating Side Shell Frame 35 - 37',
                'deliverables' => 'Replating Side Shell Frame 35 - 37',
                'duration' => 22,
                'wbs_id' => 43,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:03:05',
                'updated_at' => '2019-03-06 16:03:05',
            ),
            51 => 
            array (
                'id' => 52,
                'number' => 'Replating Internal Tank Side Shell Frame 35 - 37',
                'description' => 'Replating Internal Tank Side Shell Frame 35 - 37',
                'deliverables' => 'Replating Internal Tank Side Shell Frame 35 - 37',
                'duration' => 21,
                'wbs_id' => 43,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:03:11',
                'updated_at' => '2019-03-06 16:03:11',
            ),
            52 => 
            array (
                'id' => 53,
                'number' => 'Replating Transome Forward PS',
                'description' => 'Replating Transome Forward PS',
                'deliverables' => 'Replating Transome Forward PS',
                'duration' => 32,
                'wbs_id' => 43,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:03:28',
                'updated_at' => '2019-03-06 16:03:28',
            ),
            53 => 
            array (
                'id' => 54,
                'number' => 'Replating Transome  Forward ',
                'description' => 'Replating Transome  Forward ',
                'deliverables' => 'Replating Transome  Forward ',
                'duration' => 27,
                'wbs_id' => 43,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:03:34',
                'updated_at' => '2019-03-06 16:03:34',
            ),
            54 => 
            array (
                'id' => 55,
                'number' => 'Replating  Internal Tank Transome  Forward ',
                'description' => 'Replating  Internal Tank Transome  Forward ',
                'deliverables' => 'Replating  Internal Tank Transome  Forward ',
                'duration' => 26,
                'wbs_id' => 43,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:03:40',
                'updated_at' => '2019-03-06 16:03:40',
            ),
            55 => 
            array (
                'id' => 56,
                'number' => 'Replating Bottom SB & PS',
                'description' => 'Replating Bottom SB & PS',
                'deliverables' => 'Replating Bottom SB & PS',
                'duration' => 30,
                'wbs_id' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:08:40',
                'updated_at' => '2019-03-06 16:08:40',
            ),
            56 => 
            array (
                'id' => 57,
                'number' => 'Replating Bottom SB',
                'description' => 'Replating Bottom SB',
                'deliverables' => 'Replating Bottom SB',
                'duration' => 25,
                'wbs_id' => 56,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:08:53',
                'updated_at' => '2019-03-06 16:08:53',
            ),
            57 => 
            array (
                'id' => 61,
                'number' => 'Replating Deck',
                'description' => 'Replating Deck',
                'deliverables' => 'Replating Deck',
                'duration' => 35,
                'wbs_id' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:10:50',
                'updated_at' => '2019-03-06 16:10:50',
            ),
            58 => 
            array (
                'id' => 62,
                'number' => 'Replating Deck',
                'description' => 'Replating Deck',
                'deliverables' => 'Replating Deck',
                'duration' => 20,
                'wbs_id' => 61,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:11:03',
                'updated_at' => '2019-03-06 16:11:03',
            ),
            59 => 
            array (
                'id' => 63,
                'number' => 'Gate Door',
                'description' => 'Gate Door',
                'deliverables' => 'Gate Door',
                'duration' => 15,
                'wbs_id' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:11:39',
                'updated_at' => '2019-03-06 16:11:39',
            ),
            60 => 
            array (
                'id' => 64,
                'number' => 'Push Pad ',
                'description' => 'Push Pad ',
                'deliverables' => 'Push Pad ',
                'duration' => 35,
                'wbs_id' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:12:06',
                'updated_at' => '2019-03-06 16:12:06',
            ),
            61 => 
            array (
                'id' => 65,
                'number' => 'Push Pad ',
                'description' => 'Push Pad ',
                'deliverables' => 'Push Pad ',
                'duration' => 20,
                'wbs_id' => 64,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:12:22',
                'updated_at' => '2019-03-06 16:12:22',
            ),
            62 => 
            array (
                'id' => 66,
                'number' => 'Winch House',
                'description' => 'Winch House',
                'deliverables' => 'Winch House',
                'duration' => 30,
                'wbs_id' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:13:01',
                'updated_at' => '2019-03-06 16:13:01',
            ),
            63 => 
            array (
                'id' => 67,
                'number' => 'Freeing port ',
                'description' => 'Freeing port ',
                'deliverables' => 'Freeing port ',
                'duration' => 30,
                'wbs_id' => 5,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:13:28',
                'updated_at' => '2019-03-06 16:13:28',
            ),
            64 => 
            array (
                'id' => 68,
                'number' => 'Out Fitting',
                'description' => 'Out Fitting',
                'deliverables' => 'Out Fitting',
                'duration' => 60,
                'wbs_id' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:13:59',
                'updated_at' => '2019-03-06 16:13:59',
            ),
            65 => 
            array (
                'id' => 69,
                'number' => 'Man Hole',
                'description' => 'Man Hole',
                'deliverables' => 'Man Hole',
                'duration' => 35,
                'wbs_id' => 68,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:14:16',
                'updated_at' => '2019-03-06 16:14:16',
            ),
            66 => 
            array (
                'id' => 70,
                'number' => 'Zink Anode',
                'description' => 'Zink Anode',
                'deliverables' => 'Zink Anode',
                'duration' => 25,
                'wbs_id' => 68,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:14:21',
                'updated_at' => '2019-03-06 16:14:21',
            ),
            67 => 
            array (
                'id' => 71,
                'number' => 'Pemasangan Bolder ',
                'description' => 'Pemasangan Bolder ',
                'deliverables' => 'Pemasangan Bolder ',
                'duration' => 30,
                'wbs_id' => 68,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:14:27',
                'updated_at' => '2019-03-06 16:14:27',
            ),
            68 => 
            array (
                'id' => 72,
                'number' => 'Pemasangan lampu Navigasi',
                'description' => 'Pemasangan lampu Navigasi',
                'deliverables' => 'Pemasangan lampu Navigasi',
                'duration' => 20,
                'wbs_id' => 68,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:14:32',
                'updated_at' => '2019-03-06 16:14:32',
            ),
            69 => 
            array (
                'id' => 73,
                'number' => 'Pembuatan Towing Bracket Smit',
                'description' => 'Pembuatan Towing Bracket Smit',
                'deliverables' => 'Pembuatan Towing Bracket Smit',
                'duration' => 25,
                'wbs_id' => 68,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:14:36',
                'updated_at' => '2019-03-06 16:14:36',
            ),
            70 => 
            array (
                'id' => 74,
                'number' => 'Pembuatan Draft',
                'description' => 'Pembuatan Draft',
                'deliverables' => 'Pembuatan Draft',
                'duration' => 30,
                'wbs_id' => 68,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:14:42',
                'updated_at' => '2019-03-06 16:14:42',
            ),
            71 => 
            array (
                'id' => 75,
                'number' => 'Pembuatan Step Ladder',
                'description' => 'Pembuatan Step Ladder',
                'deliverables' => 'Pembuatan Step Ladder',
                'duration' => 35,
                'wbs_id' => 68,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:14:49',
                'updated_at' => '2019-03-06 16:14:49',
            ),
            72 => 
            array (
                'id' => 76,
            'number' => 'Pembuatan Cover Orlop ( Hole Anchor)',
            'description' => 'Pembuatan Cover Orlop ( Hole Anchor)',
            'deliverables' => 'Pembuatan Cover Orlop ( Hole Anchor)',
                'duration' => 25,
                'wbs_id' => 68,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:14:55',
                'updated_at' => '2019-03-06 16:14:55',
            ),
            73 => 
            array (
                'id' => 77,
                'number' => 'Rewelding',
                'description' => 'Rewelding',
                'deliverables' => 'Rewelding',
                'duration' => 45,
                'wbs_id' => 68,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:18:22',
                'updated_at' => '2019-03-06 16:18:22',
            ),
            74 => 
            array (
                'id' => 78,
            'number' => 'Rewelding Orlop ( Hole Anchor)',
            'description' => 'Rewelding Orlop ( Hole Anchor)',
            'deliverables' => 'Rewelding Orlop ( Hole Anchor)',
                'duration' => 25,
                'wbs_id' => 77,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:18:30',
                'updated_at' => '2019-03-06 16:18:30',
            ),
            75 => 
            array (
                'id' => 79,
                'number' => 'Rewelding Bottom',
                'description' => 'Rewelding Bottom',
                'deliverables' => 'Rewelding Bottom',
                'duration' => 25,
                'wbs_id' => 77,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:18:35',
                'updated_at' => '2019-03-06 16:18:35',
            ),
            76 => 
            array (
                'id' => 80,
                'number' => 'Rewelding SB longitudinal',
                'description' => 'Rewelding SB longitudinal',
                'deliverables' => 'Rewelding SB longitudinal',
                'duration' => 20,
                'wbs_id' => 79,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:19:13',
                'updated_at' => '2019-03-06 16:19:13',
            ),
            77 => 
            array (
                'id' => 81,
                'number' => 'Rewelding SB Transversal',
                'description' => 'Rewelding SB Transversal',
                'deliverables' => 'Rewelding SB Transversal',
                'duration' => 20,
                'wbs_id' => 79,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:19:20',
                'updated_at' => '2019-03-06 16:19:20',
            ),
            78 => 
            array (
                'id' => 82,
                'number' => 'Rewelding PS longitudinal',
                'description' => 'Rewelding PS longitudinal',
                'deliverables' => 'Rewelding PS longitudinal',
                'duration' => 15,
                'wbs_id' => 79,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:19:23',
                'updated_at' => '2019-03-06 16:19:23',
            ),
            79 => 
            array (
                'id' => 83,
                'number' => 'Rewelding PS Transversal',
                'description' => 'Rewelding PS Transversal',
                'deliverables' => 'Rewelding PS Transversal',
                'duration' => 15,
                'wbs_id' => 79,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-03-06 16:19:27',
                'updated_at' => '2019-03-06 16:19:27',
            ),
            80 => 
            array (
                'id' => 84,
                'number' => 'Other',
                'description' => 'Other',
                'deliverables' => 'Other',
                'duration' => 2,
                'wbs_id' => 3,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 11:38:32',
                'updated_at' => '2019-04-11 11:38:32',
            ),
            81 => 
            array (
                'id' => 85,
                'number' => 'Panel Block F1',
                'description' => 'Panel Block F1',
                'deliverables' => 'Panel Block F1',
                'duration' => 50,
                'wbs_id' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 14:32:35',
                'updated_at' => '2019-04-11 14:32:35',
            ),
            82 => 
            array (
                'id' => 86,
                'number' => 'Panel Block F2-F3',
                'description' => 'Panel Block F2-F3',
                'deliverables' => 'Panel Block F2-F3',
                'duration' => 50,
                'wbs_id' => 6,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 14:32:48',
                'updated_at' => '2019-04-11 14:32:48',
            ),
            83 => 
            array (
                'id' => 87,
                'number' => 'Winch House',
                'description' => 'Winch House',
                'deliverables' => 'Winch House',
                'duration' => 1,
                'wbs_id' => 68,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-12 10:30:17',
                'updated_at' => '2019-04-12 10:30:17',
            ),
            84 => 
            array (
                'id' => 88,
                'number' => 'Pembuatan 2 Pintu Besar',
                'description' => 'Pembuatan 2 Pintu Besar',
                'deliverables' => 'Pembuatan 2 Pintu Besar',
                'duration' => 1,
                'wbs_id' => 87,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-12 10:30:51',
                'updated_at' => '2019-04-12 10:30:51',
            ),
            85 => 
            array (
                'id' => 90,
                'number' => 'Pintu Forward',
                'description' => 'Pintu Forward',
                'deliverables' => 'Pintu Forward',
                'duration' => 1,
                'wbs_id' => 88,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-12 10:32:12',
                'updated_at' => '2019-04-12 10:32:12',
            ),
            86 => 
            array (
                'id' => 91,
                'number' => 'Pintu Sekat',
                'description' => 'Pintu Sekat',
                'deliverables' => 'Pintu Sekat',
                'duration' => 1,
                'wbs_id' => 88,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-12 10:32:19',
                'updated_at' => '2019-04-12 10:32:19',
            ),
        ));
        
        
    }
}