<?php

use Illuminate\Database\Seeder;

class ProActivityTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pro_activity')->delete();
        
        \DB::table('pro_activity')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'ACT192040001',
                'name' => 'Plate',
                'description' => 'Plate',
                'status' => 1,
                'wbs_id' => 7,
                'activity_configuration_id' => 186,
                'planned_duration' => 7,
                'planned_start_date' => '2019-04-27',
                'planned_end_date' => '2019-05-03',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 12.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 16:33:33',
                'updated_at' => '2019-04-12 09:36:45',
            ),
            1 => 
            array (
                'id' => 3,
                'code' => 'ACT192040002',
                'name' => 'Stiffener Line 1-5',
                'description' => 'Stiffener Line 1-5',
                'status' => 1,
                'wbs_id' => 7,
                'activity_configuration_id' => 187,
                'planned_duration' => 4,
                'planned_start_date' => '2019-05-03',
                'planned_end_date' => '2019-05-06',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 11.0,
                'predecessor' => '[[1,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 16:55:17',
                'updated_at' => '2019-04-12 09:36:58',
            ),
            2 => 
            array (
                'id' => 4,
                'code' => 'ACT192040003',
                'name' => 'Roundbar',
                'description' => 'Roundbar',
                'status' => 1,
                'wbs_id' => 7,
                'activity_configuration_id' => 188,
                'planned_duration' => 5,
                'planned_start_date' => '2019-05-06',
                'planned_end_date' => '2019-05-10',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 12.0,
                'predecessor' => '[[3,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 16:56:22',
                'updated_at' => '2019-04-12 09:36:40',
            ),
            3 => 
            array (
                'id' => 5,
                'code' => 'ACT192040004',
                'name' => 'Plate',
                'description' => 'Plate',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => 192,
                'planned_duration' => 4,
                'planned_start_date' => '2019-05-11',
                'planned_end_date' => '2019-05-14',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 4.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 23:49:34',
                'updated_at' => '2019-04-11 23:50:06',
            ),
            4 => 
            array (
                'id' => 6,
                'code' => 'ACT192040005',
                'name' => 'Strip',
                'description' => 'Strip',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => 193,
                'planned_duration' => 2,
                'planned_start_date' => '2019-05-14',
                'planned_end_date' => '2019-05-15',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 6.5,
                'predecessor' => '[[5,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 23:50:55',
                'updated_at' => '2019-04-12 09:38:37',
            ),
            5 => 
            array (
                'id' => 7,
                'code' => 'ACT192040006',
                'name' => 'Engsel',
                'description' => 'Engsel',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => 194,
                'planned_duration' => 3,
                'planned_start_date' => '2019-05-15',
                'planned_end_date' => '2019-05-17',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 6.5,
                'predecessor' => '[[6,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 23:51:27',
                'updated_at' => '2019-04-12 09:38:33',
            ),
            6 => 
            array (
                'id' => 8,
                'code' => 'ACT192040007',
                'name' => 'Plate',
                'description' => 'Plate',
                'status' => 1,
                'wbs_id' => 10,
                'activity_configuration_id' => 195,
                'planned_duration' => 2,
                'planned_start_date' => '2019-05-18',
                'planned_end_date' => '2019-05-19',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 4.5,
                'predecessor' => '[[7,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 23:53:31',
                'updated_at' => '2019-04-11 23:53:43',
            ),
            7 => 
            array (
                'id' => 9,
                'code' => 'ACT192040008',
                'name' => 'Strip',
                'description' => 'Strip',
                'status' => 1,
                'wbs_id' => 10,
                'activity_configuration_id' => 196,
                'planned_duration' => 4,
                'planned_start_date' => '2019-05-19',
                'planned_end_date' => '2019-05-22',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 6.5,
                'predecessor' => '[[8,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 23:54:32',
                'updated_at' => '2019-04-12 09:38:54',
            ),
            8 => 
            array (
                'id' => 10,
                'code' => 'ACT192040009',
                'name' => 'Engsel',
                'description' => 'Engsel',
                'status' => 1,
                'wbs_id' => 10,
                'activity_configuration_id' => 197,
                'planned_duration' => 3,
                'planned_start_date' => '2019-05-22',
                'planned_end_date' => '2019-05-24',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 6.5,
                'predecessor' => '[[9,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-11 23:55:33',
                'updated_at' => '2019-04-12 09:39:02',
            ),
            9 => 
            array (
                'id' => 11,
                'code' => 'ACT192040010',
                'name' => 'Persiapan pengedokan
',
                'description' => 'Persiapan pengedokan
',
                'status' => 1,
                'wbs_id' => 1,
                'activity_configuration_id' => 171,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-25',
                'planned_end_date' => '2019-04-25',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 2.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-12 09:07:39',
                'updated_at' => '2019-04-12 09:33:12',
            ),
            10 => 
            array (
                'id' => 12,
                'code' => 'ACT192040011',
                'name' => 'Docking',
                'description' => 'Docking',
                'status' => 1,
                'wbs_id' => 1,
                'activity_configuration_id' => 172,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-26',
                'planned_end_date' => '2019-04-26',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'predecessor' => '[[11,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-12 09:09:58',
                'updated_at' => '2019-04-12 09:15:03',
            ),
            11 => 
            array (
                'id' => 13,
                'code' => 'ACT192040012',
                'name' => 'Gambar Bukaan Kulit',
                'description' => 'Gambar Bukaan Kulit',
                'status' => 1,
                'wbs_id' => 1,
                'activity_configuration_id' => 199,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-27',
                'planned_end_date' => '2019-04-27',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'predecessor' => '[[12,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-12 09:14:53',
                'updated_at' => '2019-04-12 09:23:36',
            ),
            12 => 
            array (
                'id' => 15,
                'code' => 'ACT192040013',
                'name' => 'Undocking',
                'description' => 'Undocking',
                'status' => 1,
                'wbs_id' => 11,
                'activity_configuration_id' => 198,
                'planned_duration' => 1,
                'planned_start_date' => '2019-05-24',
                'planned_end_date' => '2019-05-24',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-12 09:26:24',
                'updated_at' => '2019-04-12 09:39:31',
            ),
            13 => 
            array (
                'id' => 16,
                'code' => 'ACT192040014',
                'name' => 'Air Pressure Test pada tangki void area perbaikan
',
                'description' => 'Air Pressure Test pada tangki void area perbaikan
',
                'status' => 1,
                'wbs_id' => 2,
                'activity_configuration_id' => 184,
                'planned_duration' => 1,
                'planned_start_date' => '2019-05-24',
                'planned_end_date' => '2019-05-24',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 6.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-12 09:27:42',
                'updated_at' => '2019-04-12 09:34:02',
            ),
            14 => 
            array (
                'id' => 17,
                'code' => 'ACT192040015',
                'name' => 'Pembuatan laporan hasil pekerjaan dan dokumen lainnya
',
                'description' => 'Pembuatan laporan hasil pekerjaan dan dokumen lainnya
',
                'status' => 1,
                'wbs_id' => 2,
                'activity_configuration_id' => 182,
                'planned_duration' => 5,
                'planned_start_date' => '2019-05-25',
                'planned_end_date' => '2019-05-29',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 6.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-04-12 09:28:24',
                'updated_at' => '2019-04-12 09:34:08',
            ),
        ));
        
        
    }
}