<?php

use Illuminate\Database\Seeder;

class ProActivityTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pro_activity')->delete();
        
        \DB::table('pro_activity')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'ACT181010001',
                'name' => 'DUMMY - Activity 1',
                'description' => 'DUMMY - Activity 1',
                'status' => 1,
                'wbs_id' => 4,
                'activity_configuration_id' => NULL,
                'planned_duration' => 7,
                'planned_start_date' => '2019-03-06',
                'planned_end_date' => '2019-03-12',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 10.0,
                'predecessor' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-19 09:40:08',
                'updated_at' => '2019-03-05 14:07:14',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'ACT181010002',
                'name' => 'DUMMY - Activity 2',
                'description' => 'DUMMY - Activity 2',
                'status' => 1,
                'wbs_id' => 4,
                'activity_configuration_id' => NULL,
                'planned_duration' => 11,
                'planned_start_date' => '2019-03-08',
                'planned_end_date' => '2019-03-18',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 8.0,
                'predecessor' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-19 09:40:27',
                'updated_at' => '2019-03-05 14:09:49',
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'ACT181010003',
                'name' => 'DUMMY - Activity 3',
                'description' => 'DUMMY - Activity 3',
                'status' => 1,
                'wbs_id' => 4,
                'activity_configuration_id' => NULL,
                'planned_duration' => 7,
                'planned_start_date' => '2019-03-20',
                'planned_end_date' => '2019-03-26',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 2.0,
                'predecessor' => '[[1,"fs"]]',
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-19 09:40:42',
                'updated_at' => '2019-03-05 14:10:32',
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'ACT181010004',
                'name' => 'DUMMY - Activity 4',
                'description' => 'DUMMY - Activity 4',
                'status' => 1,
                'wbs_id' => 5,
                'activity_configuration_id' => NULL,
                'planned_duration' => 5,
                'planned_start_date' => '2019-03-11',
                'planned_end_date' => '2019-03-15',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 15.0,
                'predecessor' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-19 09:41:40',
                'updated_at' => '2019-03-05 14:09:52',
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'ACT181010005',
                'name' => 'DUMMY - Activity 5',
                'description' => 'DUMMY - Activity 5',
                'status' => 1,
                'wbs_id' => 5,
                'activity_configuration_id' => NULL,
                'planned_duration' => 18,
                'planned_start_date' => '2019-03-18',
                'planned_end_date' => '2019-04-04',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'predecessor' => '[[4,"fs"]]',
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-19 09:42:08',
                'updated_at' => '2019-03-05 14:11:51',
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'ACT181010006',
                'name' => 'DUMMY - Activity 6',
                'description' => 'DUMMY - Activity 6',
                'status' => 1,
                'wbs_id' => 5,
                'activity_configuration_id' => NULL,
                'planned_duration' => 14,
                'planned_start_date' => '2019-03-20',
                'planned_end_date' => '2019-04-02',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'predecessor' => '[[2,"fs"]]',
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-19 09:42:22',
                'updated_at' => '2019-03-05 14:11:26',
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'ACT181010007',
                'name' => 'DUMMY - Activity 7',
                'description' => 'DUMMY - Activity 7',
                'status' => 1,
                'wbs_id' => 6,
                'activity_configuration_id' => NULL,
                'planned_duration' => 12,
                'planned_start_date' => '2019-06-03',
                'planned_end_date' => '2019-06-14',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 10.0,
                'predecessor' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-19 09:43:06',
                'updated_at' => '2019-02-26 15:25:59',
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'ACT181010008',
                'name' => 'DUMMY - Activity 8',
                'description' => 'DUMMY - Activity 8',
                'status' => 1,
                'wbs_id' => 6,
                'activity_configuration_id' => NULL,
                'planned_duration' => 12,
                'planned_start_date' => '2019-06-17',
                'planned_end_date' => '2019-06-28',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 10.0,
                'predecessor' => '[[7,"fs"]]',
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-19 09:43:27',
                'updated_at' => '2019-02-26 15:25:47',
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'ACT181010009',
                'name' => 'DUMMY - Activity 9',
                'description' => 'DUMMY - Activity 9',
                'status' => 1,
                'wbs_id' => 7,
                'activity_configuration_id' => NULL,
                'planned_duration' => 16,
                'planned_start_date' => '2019-07-01',
                'planned_end_date' => '2019-07-16',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 10.0,
                'predecessor' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-19 09:44:03',
                'updated_at' => '2019-02-26 15:26:50',
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'ACT181010010',
                'name' => 'DUMMY - Activity 10',
                'description' => 'DUMMY - Activity 10',
                'status' => 1,
                'wbs_id' => 7,
                'activity_configuration_id' => NULL,
                'planned_duration' => 15,
                'planned_start_date' => '2019-07-17',
                'planned_end_date' => '2019-07-31',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 10.0,
                'predecessor' => '[[9,"fs"]]',
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-19 09:44:33',
                'updated_at' => '2019-02-26 15:27:03',
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'ACT181010011',
                'name' => 'DUMMY - Activity 11',
                'description' => 'DUMMY - Activity 11',
                'status' => 1,
                'wbs_id' => 8,
                'activity_configuration_id' => NULL,
                'planned_duration' => 23,
                'planned_start_date' => '2019-08-01',
                'planned_end_date' => '2019-08-23',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'predecessor' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-19 09:45:28',
                'updated_at' => '2019-02-26 15:28:10',
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'ACT181010012',
                'name' => 'DUMMY - Activity 12',
                'description' => 'DUMMY - Activity 12',
                'status' => 1,
                'wbs_id' => 9,
                'activity_configuration_id' => NULL,
                'planned_duration' => 26,
                'planned_start_date' => '2019-08-26',
                'planned_end_date' => '2019-09-20',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'predecessor' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-19 09:45:58',
                'updated_at' => '2019-02-26 15:28:38',
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'ACT192010001',
                'name' => 'Act 1',
                'description' => 'Activity Repair - Dummy 1',
                'status' => 1,
                'wbs_id' => 18,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-02',
                'planned_end_date' => '2019-04-02',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 3.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:26:05',
                'updated_at' => '2019-02-25 17:26:05',
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'ACT192010002',
                'name' => 'Act 2',
                'description' => 'Activity Repair - Dummy 2',
                'status' => 1,
                'wbs_id' => 18,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-02',
                'planned_end_date' => '2019-04-02',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 3.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:26:13',
                'updated_at' => '2019-02-25 17:26:13',
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'ACT192010003',
                'name' => 'Act 3',
                'description' => 'Activity Repair - Dummy 3',
                'status' => 1,
                'wbs_id' => 18,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-02',
                'planned_end_date' => '2019-04-02',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 3.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:26:26',
                'updated_at' => '2019-02-25 17:26:26',
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'ACT192010004',
                'name' => 'Act 4',
                'description' => 'Activity Repair - Dummy 4',
                'status' => 1,
                'wbs_id' => 18,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-02',
                'planned_end_date' => '2019-04-02',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 1.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:26:43',
                'updated_at' => '2019-02-25 17:26:43',
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'ACT192010005',
                'name' => 'Act 5',
                'description' => 'Activity Repair - Dummy 5',
                'status' => 1,
                'wbs_id' => 19,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-03',
                'planned_end_date' => '2019-04-03',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:27:08',
                'updated_at' => '2019-02-25 17:27:08',
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'ACT192010006',
                'name' => 'Act 6',
                'description' => 'Activity Repair - Dummy 6',
                'status' => 1,
                'wbs_id' => 19,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-03',
                'planned_end_date' => '2019-04-03',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 10.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:27:21',
                'updated_at' => '2019-02-25 17:27:21',
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'ACT192010007',
                'name' => 'Act 7',
                'description' => 'Activity Repair - Dummy 7',
                'status' => 1,
                'wbs_id' => 20,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-05',
                'planned_end_date' => '2019-04-05',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 3.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:27:53',
                'updated_at' => '2019-02-25 17:27:53',
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'ACT192010008',
                'name' => 'Act 8',
                'description' => 'Activity Repair - Dummy 8',
                'status' => 1,
                'wbs_id' => 20,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-05',
                'planned_end_date' => '2019-04-05',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 3.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:28:04',
                'updated_at' => '2019-02-25 17:28:04',
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'ACT192010009',
                'name' => 'Act 9',
                'description' => 'Activity Repair - Dummy 9',
                'status' => 1,
                'wbs_id' => 20,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-05',
                'planned_end_date' => '2019-04-05',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 4.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:28:16',
                'updated_at' => '2019-02-25 17:28:16',
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'ACT192010010',
                'name' => 'Act 10',
                'description' => 'Activity Repair - Dummy 10',
                'status' => 1,
                'wbs_id' => 21,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-08',
                'planned_end_date' => '2019-04-08',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 3.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:28:40',
                'updated_at' => '2019-02-25 17:28:57',
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'ACT192010011',
                'name' => 'Act 11',
                'description' => 'Activity Repair - Dummy 11',
                'status' => 1,
                'wbs_id' => 21,
                'activity_configuration_id' => NULL,
                'planned_duration' => 2,
                'planned_start_date' => '2019-04-08',
                'planned_end_date' => '2019-04-09',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 1.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:28:52',
                'updated_at' => '2019-02-25 17:29:02',
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'ACT192010012',
                'name' => 'Act 12',
                'description' => 'Activity Repair - Dummy 12',
                'status' => 1,
                'wbs_id' => 21,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-09',
                'planned_end_date' => '2019-04-09',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 1.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:29:13',
                'updated_at' => '2019-02-25 17:29:13',
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'ACT192010013',
                'name' => 'Act 13',
                'description' => 'Activity Repair - Dummy 13',
                'status' => 1,
                'wbs_id' => 22,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-10',
                'planned_end_date' => '2019-04-10',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 1.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:30:36',
                'updated_at' => '2019-02-25 17:30:36',
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'ACT192010014',
                'name' => 'Act 14',
                'description' => 'Activity Repair - Dummy 14',
                'status' => 1,
                'wbs_id' => 22,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-10',
                'planned_end_date' => '2019-04-10',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 1.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:30:46',
                'updated_at' => '2019-02-25 17:30:46',
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'ACT192010015',
                'name' => 'Act 15',
                'description' => 'Activity Repair - Dummy 15',
                'status' => 1,
                'wbs_id' => 23,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-10',
                'planned_end_date' => '2019-04-10',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 1.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:31:19',
                'updated_at' => '2019-02-25 17:31:19',
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'ACT192010016',
                'name' => 'Act 16',
                'description' => 'Activity Repair - Dummy 16',
                'status' => 1,
                'wbs_id' => 23,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-10',
                'planned_end_date' => '2019-04-10',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 1.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:31:29',
                'updated_at' => '2019-02-25 17:31:29',
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'ACT192010017',
                'name' => 'Act 17',
                'description' => 'Activity Repair - Dummy 17',
                'status' => 1,
                'wbs_id' => 24,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-11',
                'planned_end_date' => '2019-04-11',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 1.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:31:45',
                'updated_at' => '2019-02-25 17:31:45',
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 'ACT192010018',
                'name' => 'Act 18',
                'description' => 'Activity Repair - Dummy 18',
                'status' => 1,
                'wbs_id' => 24,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-11',
                'planned_end_date' => '2019-04-11',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 1.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:31:55',
                'updated_at' => '2019-02-25 17:31:55',
            ),
            30 => 
            array (
                'id' => 31,
                'code' => 'ACT192010019',
                'name' => 'Act 19',
                'description' => 'Activity Repair - Dummy 19',
                'status' => 1,
                'wbs_id' => 25,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-12',
                'planned_end_date' => '2019-04-12',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 1.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:32:09',
                'updated_at' => '2019-02-25 17:32:09',
            ),
            31 => 
            array (
                'id' => 32,
                'code' => 'ACT192010020',
                'name' => 'Act 20',
                'description' => 'Activity Repair - Dummy 20',
                'status' => 1,
                'wbs_id' => 25,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-12',
                'planned_end_date' => '2019-04-12',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 1.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:32:21',
                'updated_at' => '2019-02-25 17:32:21',
            ),
            32 => 
            array (
                'id' => 33,
                'code' => 'ACT192010021',
                'name' => 'Bongkar semen & penyemenan kembali man hole',
            'description' => 'Bongkar semen & penyemenan kembali man hole (DUMMY)',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-15',
                'planned_end_date' => '2019-04-15',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 2.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:36:10',
                'updated_at' => '2019-02-25 17:37:12',
            ),
            33 => 
            array (
                'id' => 34,
                'code' => 'ACT192010022',
                'name' => 'Buta Tutup man hole',
            'description' => 'Buta Tutup man hole (DUMMY)',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-15',
                'planned_end_date' => '2019-04-15',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 3.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:37:27',
                'updated_at' => '2019-02-25 17:37:27',
            ),
            34 => 
            array (
                'id' => 35,
                'code' => 'ACT192010023',
                'name' => 'Ganti packing karte man hole',
            'description' => 'Ganti packing karte man hole (DUMMY)',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-16',
                'planned_end_date' => '2019-04-16',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 3.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:37:43',
                'updated_at' => '2019-02-25 17:37:43',
            ),
            35 => 
            array (
                'id' => 36,
                'code' => 'ACT192010024',
                'name' => 'Bongkar man hole lama',
            'description' => 'Bongkar man hole lama (DUMMY)',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-16',
                'planned_end_date' => '2019-04-16',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 2.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:37:57',
                'updated_at' => '2019-02-25 17:37:57',
            ),
            36 => 
            array (
                'id' => 37,
                'code' => 'ACT192010025',
                'name' => 'Tutup man hole lama',
            'description' => 'Tutup man hole lama (DUMMY)',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-17',
                'planned_end_date' => '2019-04-17',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 2.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:38:18',
                'updated_at' => '2019-02-25 17:38:18',
            ),
            37 => 
            array (
                'id' => 38,
                'code' => 'ACT192010026',
                'name' => 'Pemasangan man hole long\' bull head',
            'description' => 'Pemasangan man hole long\' bull head (DUMMY)',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-17',
                'planned_end_date' => '2019-04-17',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 3.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:38:39',
                'updated_at' => '2019-02-25 17:38:39',
            ),
            38 => 
            array (
                'id' => 39,
                'code' => 'ACT192010027',
                'name' => 'Sounding plug',
            'description' => 'Sounding plug (DUMMY)',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => NULL,
                'planned_duration' => 2,
                'planned_start_date' => '2019-04-17',
                'planned_end_date' => '2019-04-18',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 3.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:38:59',
                'updated_at' => '2019-02-25 17:38:59',
            ),
            39 => 
            array (
                'id' => 40,
                'code' => 'ACT192010028',
                'name' => 'Penggantian bolt & nut',
            'description' => 'Penggantian bolt & nut (DUMMY)',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-18',
                'planned_end_date' => '2019-04-18',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 2.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:39:32',
                'updated_at' => '2019-02-25 17:39:32',
            ),
            40 => 
            array (
                'id' => 41,
                'code' => 'ACT192010029',
                'name' => 'Cleaning Tank',
            'description' => 'Cleaning Tank (DUMMY)',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-18',
                'planned_end_date' => '2019-04-18',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:39:46',
                'updated_at' => '2019-02-25 17:39:46',
            ),
            41 => 
            array (
                'id' => 42,
                'code' => 'ACT192010030',
                'name' => 'Bongkar & Pemasangan baru zink anode',
            'description' => 'Bongkar & Pemasangan baru zink anode (DUMMY)',
                'status' => 1,
                'wbs_id' => 13,
                'activity_configuration_id' => NULL,
                'planned_duration' => 4,
                'planned_start_date' => '2019-04-19',
                'planned_end_date' => '2019-04-22',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 15.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:40:27',
                'updated_at' => '2019-02-25 17:40:27',
            ),
            42 => 
            array (
                'id' => 43,
                'code' => 'ACT192010031',
                'name' => 'Bongkar Bolder Kn/Ki double lama',
                'description' => 'Bongkar Bolder Kn/Ki double lama',
                'status' => 1,
                'wbs_id' => 14,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-23',
                'planned_end_date' => '2019-04-23',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:42:05',
                'updated_at' => '2019-02-25 17:42:05',
            ),
            43 => 
            array (
                'id' => 44,
                'code' => 'ACT192010032',
                'name' => 'Pemasangan Penambahan Bolder Kn/Ki double baru',
                'description' => 'Pemasangan Penambahan Bolder Kn/Ki double baru',
                'status' => 1,
                'wbs_id' => 14,
                'activity_configuration_id' => NULL,
                'planned_duration' => 1,
                'planned_start_date' => '2019-04-24',
                'planned_end_date' => '2019-04-24',
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => '2019-02-25 17:42:35',
                'updated_at' => '2019-02-25 17:42:35',
            ),
        ));
        
        
    }
}