<?php

use Illuminate\Database\Seeder;

class ProProjectTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pro_project')->delete();
        
        \DB::table('pro_project')->insert(array (
            0 => 
            array (
                'id' => 1,
                'number' => 'PROJECT-01',
                'drawing' => NULL,
                'business_unit_id' => 1,
                'project_sequence' => 1,
                'ship_id' => 1,
                'customer_id' => 4,
                'name' => 'Tug Boat Project',
                'description' => 'pertama kali',
                'sales_order_id' => NULL,
                'planned_start_date' => '2018-08-16',
                'planned_end_date' => '2018-12-30',
                'planned_duration' => '137',
                'actual_start_date' => '2018-08-17',
                'actual_end_date' => '2018-12-31',
                'actual_duration' => '137',
                'progress' => 0.0,
                'flag' => 'INDONESIA',
                'class_name' => NULL,
                'class_contact_person_name' => NULL,
                'class_contact_person_phone' => NULL,
                'class_contact_person_email' => NULL,
                'status' => 1,
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-18 00:00:00',
                'updated_at' => '2018-12-18 00:00:00',
            ),
            1 => 
            array (
                'id' => 2,
                'number' => 'PROJECT-02',
                'drawing' => NULL,
                'business_unit_id' => 1,
                'project_sequence' => 2,
                'ship_id' => 2,
                'customer_id' => 2,
                'name' => 'OIL BARGE 1100KL PROJECT',
                'description' => 'Real Case',
                'sales_order_id' => NULL,
                'planned_start_date' => '2018-12-29',
                'planned_end_date' => '2019-05-28',
                'planned_duration' => '151',
                'actual_start_date' => '2018-12-29',
                'actual_end_date' => '2019-05-28',
                'actual_duration' => '151',
                'progress' => 0.0,
                'flag' => 'INDONESIA',
                'class_name' => NULL,
                'class_contact_person_name' => NULL,
                'class_contact_person_phone' => NULL,
                'class_contact_person_email' => NULL,
                'status' => 1,
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-18 00:00:00',
                'updated_at' => '2018-12-18 00:00:00',
            ),
            2 => 
            array (
                'id' => 3,
                'number' => 'PROJECT-03',
                'drawing' => NULL,
                'business_unit_id' => 2,
                'project_sequence' => 3,
                'ship_id' => 3,
                'customer_id' => 1,
                'name' => 'Offshore Supply Vessel Project',
                'description' => 'ketiga kali',
                'sales_order_id' => NULL,
                'planned_start_date' => '2018-08-16',
                'planned_end_date' => '2019-01-16',
                'planned_duration' => '154',
                'actual_start_date' => '2018-08-16',
                'actual_end_date' => '2019-01-16',
                'actual_duration' => '154',
                'progress' => 0.0,
                'flag' => 'INDONESIA',
                'class_name' => NULL,
                'class_contact_person_name' => NULL,
                'class_contact_person_phone' => NULL,
                'class_contact_person_email' => NULL,
                'status' => 1,
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-18 00:00:00',
                'updated_at' => '2018-12-18 00:00:00',
            ),
            3 => 
            array (
                'id' => 4,
                'number' => 'PROJECT-04',
                'drawing' => NULL,
                'business_unit_id' => 2,
                'project_sequence' => 4,
                'ship_id' => 4,
                'customer_id' => 3,
                'name' => 'Deck Cargo Barge Project',
                'description' => 'pertama kali',
                'sales_order_id' => NULL,
                'planned_start_date' => '2018-08-16',
                'planned_end_date' => '2018-11-16',
                'planned_duration' => '93',
                'actual_start_date' => '2018-08-20',
                'actual_end_date' => '2018-12-01',
                'actual_duration' => '104',
                'progress' => 0.0,
                'flag' => 'INDONESIA',
                'class_name' => NULL,
                'class_contact_person_name' => NULL,
                'class_contact_person_phone' => NULL,
                'class_contact_person_email' => NULL,
                'status' => 1,
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-18 00:00:00',
                'updated_at' => '2018-12-18 00:00:00',
            ),
            4 => 
            array (
                'id' => 5,
                'number' => 'PRO-DUMMY01',
                'drawing' => NULL,
                'business_unit_id' => 1,
                'project_sequence' => 5,
                'ship_id' => 1,
                'customer_id' => 20,
                'name' => 'Project Dummy 01',
                'description' => 'Project Dummy 01',
                'sales_order_id' => NULL,
                'planned_start_date' => '2018-12-16',
                'planned_end_date' => '2019-01-31',
                'planned_duration' => '47',
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'actual_duration' => NULL,
                'progress' => 0.0,
                'flag' => 'DUMMY - INDONESIA',
                'class_name' => 'DUMMY - BKI',
                'class_contact_person_name' => 'DUMMY - Aldies',
                'class_contact_person_phone' => '0896531332',
                'class_contact_person_email' => 'dummy.aldies@dummy.com',
                'status' => 1,
                'user_id' => 5,
                'branch_id' => 1,
                'created_at' => '2018-12-18 00:00:00',
                'updated_at' => '2018-12-18 00:00:00',
            ),
            5 => 
            array (
                'id' => 6,
                'number' => 'DUMMY',
                'drawing' => NULL,
                'business_unit_id' => 1,
                'project_sequence' => 6,
                'ship_id' => 1,
                'customer_id' => 1,
                'name' => 'AndroDummy',
                'description' => 'Tgb',
                'sales_order_id' => NULL,
                'planned_start_date' => '2018-12-01',
                'planned_end_date' => '2019-02-28',
                'planned_duration' => '90',
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'actual_duration' => NULL,
                'progress' => 0.0,
                'flag' => 'INDONESIA',
                'class_name' => 'BKI',
                'class_contact_person_name' => 'BUDI',
                'class_contact_person_phone' => '0817777222',
                'class_contact_person_email' => 'BUDI@BKI.COM',
                'status' => 1,
                'user_id' => 6,
                'branch_id' => 1,
                'created_at' => '2018-12-18 16:23:38',
                'updated_at' => '2018-12-18 18:23:21',
            ),
        ));
        
        
    }
}