<?php

use Illuminate\Database\Seeder;

class ProWbsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pro_wbs')->delete();
        
        \DB::table('pro_wbs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'WBS181010001',
                'name' => 'WBS 1',
                'description' => 'WBS 1',
                'deliverables' => 'Satu',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-09-30',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'WBS181010002',
                'name' => 'WBS 1.1',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 1,
                'wbs_id' => 1,
                'status' => 1,
                'planned_deadline' => '2018-09-30',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'WBS181010003',
                'name' => 'WBS 1.2',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 1,
                'wbs_id' => 1,
                'status' => 1,
                'planned_deadline' => '2018-09-30',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'WBS181010004',
                'name' => 'WBS 1.1.1',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 1,
                'wbs_id' => 2,
                'status' => 1,
                'planned_deadline' => '2018-09-30',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'WBS181010005',
                'name' => 'WBS 1.1.1.1',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 4,
                'status' => 1,
                'planned_deadline' => '2018-09-30',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'WBS181010006',
                'name' => 'WBS 1.1.1.1.1',
                'description' => '',
                'deliverables' => 'Level 5',
                'project_id' => 1,
                'wbs_id' => 5,
                'status' => 1,
                'planned_deadline' => '2018-09-30',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'WBS181010007',
                'name' => 'WBS 2',
                'description' => '',
                'deliverables' => 'WBS 2 Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-09-10',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'WBS181010008',
                'name' => 'WBS 2.1',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-12-22',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'WBS181010009',
                'name' => 'WBS 3',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-12-22',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'WBS181010010',
                'name' => 'WBS2 1',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-02-22',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'WBS181010011',
                'name' => 'WBS2 1.2',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 1,
                'wbs_id' => 10,
                'status' => 1,
                'planned_deadline' => '2019-01-05',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'WBS181010012',
                'name' => 'WBS2 2',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-03-15',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'WBS181010013',
                'name' => 'WBS2 2.1',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 1,
                'wbs_id' => 12,
                'status' => 1,
                'planned_deadline' => '2019-02-25',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'WBS181010014',
                'name' => 'WBS2 2.2',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 1,
                'wbs_id' => 12,
                'status' => 1,
                'planned_deadline' => '2019-03-07',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'WBS181010015',
                'name' => 'WBS2 3',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-06-18',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'WBS181010016',
                'name' => 'WBS2 3.1',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 1,
                'wbs_id' => 15,
                'status' => 1,
                'planned_deadline' => '2019-06-06',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'WBS181010017',
                'name' => 'WBS3 1',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-11-27',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'WBS181010018',
                'name' => 'WBS3 2',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-10-15',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'WBS181010019',
                'name' => 'WBS4 1',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-09-09',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'WBS181010020',
                'name' => 'WBS4 2',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-10-29',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'WBS181020001',
                'name' => 'CONTRACT SIGN',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 2,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-12-29',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'WBS181020002',
                'name' => 'APPROVED DESIGN, SPECIFICATION & SHIP DOCUMENT',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 2,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-12-29',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'WBS181020003',
                'name' => 'Design Drawings & Submission',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 2,
                'wbs_id' => 22,
                'status' => 1,
                'planned_deadline' => '2019-01-31',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'WBS181020004',
                'name' => 'Distribution DWG to stakeholder',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 2,
                'wbs_id' => 22,
                'status' => 1,
                'planned_deadline' => '2019-05-28',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'WBS181020005',
                'name' => 'Procurement Process',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 2,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-04-10',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'WBS181020006',
                'name' => 'Production Process',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 2,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-05-21',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'WBS181020007',
                'name' => 'Hull Structure',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 2,
                'wbs_id' => 26,
                'status' => 1,
                'planned_deadline' => '2019-05-21',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'WBS181020008',
                'name' => 'Bottom',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 2,
                'wbs_id' => 27,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'WBS181020009',
                'name' => 'Transom',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 28,
                'status' => 1,
                'planned_deadline' => '2019-02-26',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 'WBS181020010',
            'name' => 'Blok 1 (Fr. 0-15)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 28,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'code' => 'WBS181020011',
            'name' => 'Master Block 2 (frame 15-21)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 28,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'code' => 'WBS181020012',
            'name' => 'Block 3 (frame 21-25)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 28,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'code' => 'WBS181020013',
            'name' => 'Block 4 (frame 25-30)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 28,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'code' => 'WBS181020014',
            'name' => 'Block 5 (frame 30-34)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 28,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'code' => 'WBS181020015',
            'name' => 'Block 6 (frame 34-43)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 28,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'code' => 'WBS181020016',
                'name' => 'Tank top',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 2,
                'wbs_id' => 27,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'code' => 'WBS181020017',
            'name' => 'Blok 1 (Fr. 0-15)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 36,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'code' => 'WBS181020018',
            'name' => 'Master Block 2 (Fr. 15-21)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 36,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'code' => 'WBS181020019',
            'name' => 'Block 3 (Fr. 21-25)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 36,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'code' => 'WBS181020020',
            'name' => 'Block 4 (Fr. 25-30)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 36,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'code' => 'WBS181020036',
            'name' => 'Block 5 (Fr. 30-34)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 36,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'code' => 'WBS181020037',
            'name' => 'Block 6 (Fr. 34-40)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 36,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'code' => 'WBS181020038',
                'name' => 'Transbulkhead',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 2,
                'wbs_id' => 27,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'code' => 'WBS181020039',
            'name' => 'Blok 1 (Fr. 0-15)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 43,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'code' => 'WBS181020040',
            'name' => 'Master Block 2 (Fr. 15-21)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 43,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'code' => 'WBS181020041',
            'name' => 'Block 3 (Fr. 21-25)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 43,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'code' => 'WBS181020042',
            'name' => 'Block 4 (Fr. 25-30)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 43,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'code' => 'WBS181020043',
            'name' => 'Block 6 (Fr. 34-40)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 43,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'code' => 'WBS181020044',
                'name' => 'Longbulkhead',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 2,
                'wbs_id' => 27,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'code' => 'WBS181020046',
            'name' => 'Master Block 2 (Fr. 15-21)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 49,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'code' => 'WBS181020047',
            'name' => 'Block 3 (Fr. 21-25)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 49,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'code' => 'WBS181020048',
            'name' => 'Block 4 (Fr. 25-30)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 49,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'code' => 'WBS181020049',
            'name' => 'Block 5 (Fr. 30-34)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 49,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'code' => 'WBS181020050',
            'name' => 'Block 6 (Fr. 34-40)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 49,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'code' => 'WBS181020051',
                'name' => 'Side sheel',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 2,
                'wbs_id' => 27,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'code' => 'WBS181020052',
            'name' => 'Blok 1 (Fr. 0-15)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'code' => 'WBS181020053',
            'name' => 'Master Block 2 (Fr. 15-21)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'code' => 'WBS181020054',
            'name' => 'Block 3 (Fr. 21-25)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'code' => 'WBS181020055',
            'name' => 'Block 4 (Fr. 25-30)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'code' => 'WBS181020056',
            'name' => 'Block 5 (Fr. 30-34)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'code' => 'WBS181020057',
            'name' => 'Block 6 (Fr. 34-40)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'code' => 'WBS181020058',
                'name' => 'Main deck',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 2,
                'wbs_id' => 27,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'code' => 'WBS181020059',
            'name' => 'Blok 1 (Fr. 0-15)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 62,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'code' => 'WBS181020060',
            'name' => 'Master Block 2 (Fr. 15-21)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 62,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'code' => 'WBS181020061',
            'name' => 'Block 3 (Fr. 21-25)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 62,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'code' => 'WBS181020062',
            'name' => 'Block 4 (Fr. 25-30)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 62,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'code' => 'WBS181020063',
            'name' => 'Block 5 (Fr. 30-34)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 62,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'code' => 'WBS181020064',
            'name' => 'Block 6 (Fr. 34-40)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 62,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'code' => 'WBS181020065',
            'name' => 'Block 8 (deck house)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 62,
                'status' => 1,
                'planned_deadline' => '2019-04-13',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'code' => 'WBS181020066',
            'name' => 'Block 9 (winch house)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 62,
                'status' => 1,
                'planned_deadline' => '2019-04-13',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'code' => 'WBS181020067',
            'name' => 'Block 7 (skeg)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 62,
                'status' => 1,
                'planned_deadline' => '2019-04-09',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'code' => 'WBS181020068',
                'name' => 'Outfitting Hull',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 2,
                'wbs_id' => 27,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'code' => 'WBS181020069',
                'name' => 'Fabrication',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 72,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'code' => 'WBS181020070',
                'name' => 'Installation',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 72,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'code' => 'WBS181020071',
                'name' => 'Piping & Safety System',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 2,
                'wbs_id' => 27,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'code' => 'WBS181020072',
                'name' => 'Cargo System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 75,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'code' => 'WBS181020073',
                'name' => 'General Service & Fire Fighting System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 75,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'code' => 'WBS181020074',
                'name' => 'Bilge & OWS System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 75,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'code' => 'WBS181020075',
                'name' => 'Emergency Fire Fighting System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 75,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'code' => 'WBS181020076',
                'name' => 'Freshwater & Sea Water System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 75,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'code' => 'WBS181020077',
                'name' => 'Fuel Oil System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 75,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'code' => 'WBS181020078',
                'name' => 'Holding Tank & Sewage System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 75,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'code' => 'WBS181020021',
                'name' => 'Air Compressor & Air Pressure',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 75,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'code' => 'WBS181020079',
                'name' => 'CO2 Fixed System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 75,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'code' => 'WBS181020080',
                'name' => 'Electric & Mechanic',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 2,
                'wbs_id' => 27,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'code' => 'WBS181020081',
                'name' => 'Electric Installation',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 85,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'code' => 'WBS181020082',
                'name' => 'Mechanic Installation',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 2,
                'wbs_id' => 85,
                'status' => 1,
                'planned_deadline' => '2019-04-06',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'code' => 'WBS181020083',
                'name' => 'Coating',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 2,
                'wbs_id' => 27,
                'status' => 1,
                'planned_deadline' => '2019-05-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'code' => 'WBS181020084',
                'name' => 'Interior and Furniture',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 2,
                'wbs_id' => 27,
                'status' => 1,
                'planned_deadline' => '2019-05-21',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'code' => 'WBS181020085',
                'name' => 'Launching',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 2,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-04-27',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'code' => 'WBS181020086',
                'name' => 'Testing Commisioning and Familirisasion',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 2,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-05-15',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'code' => 'WBS181020087',
                'name' => 'DELIVERY',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 2,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-05-28',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'code' => 'WBS181030001',
                'name' => 'DUMMY - Hull',
                'description' => 'DUMMY',
                'deliverables' => 'Hull',
                'project_id' => 5,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-01-15',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 50.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 00:00:00',
                'updated_at' => '2018-12-18 00:00:00',
            ),
            93 => 
            array (
                'id' => 94,
                'code' => 'WBS181030002',
                'name' => 'DUMMY - Outfitting',
                'description' => 'DUMMY',
                'deliverables' => 'Outfitting',
                'project_id' => 5,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-01-22',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 50.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 00:00:00',
                'updated_at' => '2018-12-18 00:00:00',
            ),
            94 => 
            array (
                'id' => 95,
                'code' => 'WBS181030003',
                'name' => 'DUMMY - Lambung',
                'description' => 'DUMMY',
                'deliverables' => 'Lambung',
                'project_id' => 5,
                'wbs_id' => 93,
                'status' => 1,
                'planned_deadline' => '2019-01-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 25.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 00:00:00',
                'updated_at' => '2018-12-18 00:00:00',
            ),
            95 => 
            array (
                'id' => 96,
                'code' => 'WBS181030004',
                'name' => 'DUMMY - Portside',
                'description' => 'DUMMY',
                'deliverables' => 'Portside',
                'project_id' => 5,
                'wbs_id' => 93,
                'status' => 1,
                'planned_deadline' => '2019-01-10',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 15.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 00:00:00',
                'updated_at' => '2018-12-18 00:00:00',
            ),
            96 => 
            array (
                'id' => 97,
                'code' => 'WBS181030005',
                'name' => 'DUMMY - Bulbous Bow',
                'description' => 'DUMMY',
                'deliverables' => 'Bulbous Bow',
                'project_id' => 5,
                'wbs_id' => 93,
                'status' => 1,
                'planned_deadline' => '2019-01-14',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 10.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 00:00:00',
                'updated_at' => '2018-12-18 00:00:00',
            ),
            97 => 
            array (
                'id' => 98,
                'code' => 'WBS181030006',
                'name' => 'DUMMY - Fabrication',
                'description' => 'DUMMY',
                'deliverables' => 'Fabrication',
                'project_id' => 5,
                'wbs_id' => 94,
                'status' => 1,
                'planned_deadline' => '2019-01-25',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 25.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 00:00:00',
                'updated_at' => '2018-12-18 00:00:00',
            ),
            98 => 
            array (
                'id' => 99,
                'code' => 'WBS181030007',
                'name' => 'DUMMY - Installation',
                'description' => 'DUMMY',
                'deliverables' => 'Installation',
                'project_id' => 5,
                'wbs_id' => 94,
                'status' => 1,
                'planned_deadline' => '2019-01-28',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 25.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 00:00:00',
                'updated_at' => '2018-12-18 00:00:00',
            ),
            99 => 
            array (
                'id' => 100,
                'code' => 'WBS181040001',
                'name' => 'Hull',
                'description' => 'Hull',
                'deliverables' => 'Hull',
                'project_id' => 6,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-12-31',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 40.0,
                'user_id' => 6,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 16:24:09',
                'updated_at' => '2018-12-18 18:23:21',
            ),
            100 => 
            array (
                'id' => 101,
                'code' => 'WBS181040002',
                'name' => 'Outfitting',
                'description' => 'Outfitting',
                'deliverables' => 'Outfitting',
                'project_id' => 6,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-01-31',
                'actual_deadline' => NULL,
                'earliest_activity' => '2019-01-23',
                'progress' => 0.0,
                'weight' => 30.0,
                'user_id' => 6,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 16:24:27',
                'updated_at' => '2018-12-18 16:47:54',
            ),
            101 => 
            array (
                'id' => 102,
                'code' => 'WBS181040003',
                'name' => 'Delivery',
                'description' => 'Delivery',
                'deliverables' => 'Delivery',
                'project_id' => 6,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-02-28',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 20.0,
                'user_id' => 6,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 16:24:43',
                'updated_at' => '2018-12-18 16:24:56',
            ),
            102 => 
            array (
                'id' => 103,
                'code' => 'WBS181040004',
                'name' => 'Hull #1',
                'description' => 'Hull #1',
                'deliverables' => 'Hull #1',
                'project_id' => 6,
                'wbs_id' => 100,
                'status' => 1,
                'planned_deadline' => '2018-12-12',
                'actual_deadline' => NULL,
                'earliest_activity' => '2018-12-01',
                'progress' => 0.0,
                'weight' => 20.0,
                'user_id' => 6,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 16:25:23',
                'updated_at' => '2018-12-18 18:23:21',
            ),
            103 => 
            array (
                'id' => 104,
                'code' => 'WBS181040005',
                'name' => 'Hull #2',
                'description' => 'Hull #2',
                'deliverables' => 'Hull #2',
                'project_id' => 6,
                'wbs_id' => 100,
                'status' => 1,
                'planned_deadline' => '2018-12-31',
                'actual_deadline' => NULL,
                'earliest_activity' => '2018-12-12',
                'progress' => 0.0,
                'weight' => 20.0,
                'user_id' => 6,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 16:25:50',
                'updated_at' => '2018-12-18 16:50:06',
            ),
            104 => 
            array (
                'id' => 105,
                'code' => 'WBS181040006',
                'name' => 'Outfitting #1',
                'description' => 'Outfitting #1',
                'deliverables' => 'Outfitting #1',
                'project_id' => 6,
                'wbs_id' => 101,
                'status' => 1,
                'planned_deadline' => '2019-01-09',
                'actual_deadline' => NULL,
                'earliest_activity' => '2018-12-31',
                'progress' => 0.0,
                'weight' => 9.8,
                'user_id' => 6,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 16:26:30',
                'updated_at' => '2018-12-18 16:43:33',
            ),
            105 => 
            array (
                'id' => 106,
                'code' => 'WBS181040007',
                'name' => 'Outfitting #2',
                'description' => 'Outfitting #2',
                'deliverables' => 'Outfitting #2',
                'project_id' => 6,
                'wbs_id' => 101,
                'status' => 1,
                'planned_deadline' => '2019-01-23',
                'actual_deadline' => NULL,
                'earliest_activity' => '2019-01-09',
                'progress' => 0.0,
                'weight' => 10.2,
                'user_id' => 6,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 16:26:43',
                'updated_at' => '2018-12-18 16:47:22',
            ),
            106 => 
            array (
                'id' => 107,
                'code' => 'WBS181040008',
                'name' => 'Dokumen',
                'description' => 'Dokumen',
                'deliverables' => 'Dokumen',
                'project_id' => 6,
                'wbs_id' => 102,
                'status' => 1,
                'planned_deadline' => '2019-02-13',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 10.0,
                'user_id' => 6,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 16:27:15',
                'updated_at' => '2018-12-18 16:27:15',
            ),
            107 => 
            array (
                'id' => 108,
                'code' => 'WBS181040009',
                'name' => 'Delivery Kapal',
                'description' => 'Delivery Kapal',
                'deliverables' => 'Delivery Kapal',
                'project_id' => 6,
                'wbs_id' => 102,
                'status' => 1,
                'planned_deadline' => '2019-02-28',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 10.0,
                'user_id' => 6,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-18 16:27:26',
                'updated_at' => '2018-12-18 16:27:26',
            ),
        ));
        
        
    }
}