<?php

use Illuminate\Database\Seeder;

class TrxPurchaseRequisitionDetailTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('trx_purchase_requisition_detail')->delete();
        
        \DB::table('trx_purchase_requisition_detail')->insert(array (
            0 => 
            array (
                'id' => 1,
                'purchase_requisition_id' => 1,
                'quantity' => 1351,
                'reserved' => 0,
                'material_id' => 5,
                'resource_id' => NULL,
                'wbs_id' => 12,
                'alocation' => 'Stock',
                'created_at' => '2019-01-15 09:57:55',
                'updated_at' => '2019-01-15 09:57:55',
            ),
            1 => 
            array (
                'id' => 2,
                'purchase_requisition_id' => 2,
                'quantity' => 23,
                'reserved' => 0,
                'material_id' => 5,
                'resource_id' => NULL,
                'wbs_id' => 4,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 04:30:38',
                'updated_at' => '2019-01-17 04:30:38',
            ),
            2 => 
            array (
                'id' => 3,
                'purchase_requisition_id' => 2,
                'quantity' => 15,
                'reserved' => 0,
                'material_id' => 4,
                'resource_id' => NULL,
                'wbs_id' => 4,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 04:30:38',
                'updated_at' => '2019-01-17 04:30:38',
            ),
            3 => 
            array (
                'id' => 4,
                'purchase_requisition_id' => 2,
                'quantity' => 8,
                'reserved' => 0,
                'material_id' => 1,
                'resource_id' => NULL,
                'wbs_id' => 6,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 04:30:38',
                'updated_at' => '2019-01-17 04:30:38',
            ),
            4 => 
            array (
                'id' => 5,
                'purchase_requisition_id' => 2,
                'quantity' => 12,
                'reserved' => 0,
                'material_id' => 7,
                'resource_id' => NULL,
                'wbs_id' => 6,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 04:30:38',
                'updated_at' => '2019-01-17 04:30:38',
            ),
            5 => 
            array (
                'id' => 6,
                'purchase_requisition_id' => 2,
                'quantity' => 3,
                'reserved' => 0,
                'material_id' => 25,
                'resource_id' => NULL,
                'wbs_id' => 5,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 04:30:38',
                'updated_at' => '2019-01-17 04:30:38',
            ),
            6 => 
            array (
                'id' => 7,
                'purchase_requisition_id' => 3,
                'quantity' => 2,
                'reserved' => 0,
                'material_id' => NULL,
                'resource_id' => 1,
                'wbs_id' => 4,
                'alocation' => NULL,
                'created_at' => '2019-01-17 04:31:13',
                'updated_at' => '2019-01-17 04:31:13',
            ),
            7 => 
            array (
                'id' => 8,
                'purchase_requisition_id' => 3,
                'quantity' => 3,
                'reserved' => 0,
                'material_id' => NULL,
                'resource_id' => 3,
                'wbs_id' => 4,
                'alocation' => NULL,
                'created_at' => '2019-01-17 04:31:13',
                'updated_at' => '2019-01-17 04:31:13',
            ),
            8 => 
            array (
                'id' => 9,
                'purchase_requisition_id' => 4,
                'quantity' => 15,
                'reserved' => 15,
                'material_id' => 2,
                'resource_id' => NULL,
                'wbs_id' => 4,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 04:33:59',
                'updated_at' => '2019-01-17 04:35:15',
            ),
            9 => 
            array (
                'id' => 10,
                'purchase_requisition_id' => 4,
                'quantity' => 8,
                'reserved' => 0,
                'material_id' => 3,
                'resource_id' => NULL,
                'wbs_id' => 4,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 04:33:59',
                'updated_at' => '2019-01-17 04:33:59',
            ),
            10 => 
            array (
                'id' => 11,
                'purchase_requisition_id' => 4,
                'quantity' => 3,
                'reserved' => 3,
                'material_id' => 33,
                'resource_id' => NULL,
                'wbs_id' => 6,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 04:33:59',
                'updated_at' => '2019-01-17 04:35:15',
            ),
            11 => 
            array (
                'id' => 12,
                'purchase_requisition_id' => 4,
                'quantity' => 2,
                'reserved' => 0,
                'material_id' => 39,
                'resource_id' => NULL,
                'wbs_id' => 4,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 04:33:59',
                'updated_at' => '2019-01-17 04:33:59',
            ),
            12 => 
            array (
                'id' => 13,
                'purchase_requisition_id' => 5,
                'quantity' => 3,
                'reserved' => 2,
                'material_id' => NULL,
                'resource_id' => 2,
                'wbs_id' => 4,
                'alocation' => NULL,
                'created_at' => '2019-01-17 04:34:34',
                'updated_at' => '2019-01-17 06:49:44',
            ),
            13 => 
            array (
                'id' => 14,
                'purchase_requisition_id' => 5,
                'quantity' => 1,
                'reserved' => 0,
                'material_id' => NULL,
                'resource_id' => 4,
                'wbs_id' => 6,
                'alocation' => NULL,
                'created_at' => '2019-01-17 04:34:34',
                'updated_at' => '2019-01-17 04:34:34',
            ),
            14 => 
            array (
                'id' => 15,
                'purchase_requisition_id' => 6,
                'quantity' => 15,
                'reserved' => 0,
                'material_id' => 36,
                'resource_id' => NULL,
                'wbs_id' => 12,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 04:40:37',
                'updated_at' => '2019-01-17 04:40:37',
            ),
            15 => 
            array (
                'id' => 16,
                'purchase_requisition_id' => 6,
                'quantity' => 5,
                'reserved' => 0,
                'material_id' => 44,
                'resource_id' => NULL,
                'wbs_id' => 14,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 04:40:37',
                'updated_at' => '2019-01-17 04:40:37',
            ),
            16 => 
            array (
                'id' => 17,
                'purchase_requisition_id' => 6,
                'quantity' => 8,
                'reserved' => 0,
                'material_id' => 35,
                'resource_id' => NULL,
                'wbs_id' => 13,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 04:40:38',
                'updated_at' => '2019-01-17 04:40:38',
            ),
            17 => 
            array (
                'id' => 18,
                'purchase_requisition_id' => 6,
                'quantity' => 5,
                'reserved' => 0,
                'material_id' => 46,
                'resource_id' => NULL,
                'wbs_id' => 14,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 04:40:38',
                'updated_at' => '2019-01-17 04:40:38',
            ),
            18 => 
            array (
                'id' => 19,
                'purchase_requisition_id' => 7,
                'quantity' => 2,
                'reserved' => 0,
                'material_id' => NULL,
                'resource_id' => 2,
                'wbs_id' => 12,
                'alocation' => NULL,
                'created_at' => '2019-01-17 04:41:15',
                'updated_at' => '2019-01-17 04:41:15',
            ),
            19 => 
            array (
                'id' => 20,
                'purchase_requisition_id' => 7,
                'quantity' => 3,
                'reserved' => 0,
                'material_id' => NULL,
                'resource_id' => 3,
                'wbs_id' => 13,
                'alocation' => NULL,
                'created_at' => '2019-01-17 04:41:15',
                'updated_at' => '2019-01-17 04:41:15',
            ),
            20 => 
            array (
                'id' => 21,
                'purchase_requisition_id' => 8,
                'quantity' => 15,
                'reserved' => 0,
                'material_id' => 4,
                'resource_id' => NULL,
                'wbs_id' => 12,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 04:42:14',
                'updated_at' => '2019-01-17 04:42:14',
            ),
            21 => 
            array (
                'id' => 22,
                'purchase_requisition_id' => 8,
                'quantity' => 8,
                'reserved' => 8,
                'material_id' => 5,
                'resource_id' => NULL,
                'wbs_id' => 12,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 04:42:15',
                'updated_at' => '2019-01-17 04:43:52',
            ),
            22 => 
            array (
                'id' => 23,
                'purchase_requisition_id' => 8,
                'quantity' => 5,
                'reserved' => 5,
                'material_id' => 19,
                'resource_id' => NULL,
                'wbs_id' => 13,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 04:42:15',
                'updated_at' => '2019-01-17 04:43:53',
            ),
            23 => 
            array (
                'id' => 24,
                'purchase_requisition_id' => 8,
                'quantity' => 5,
                'reserved' => 0,
                'material_id' => 21,
                'resource_id' => NULL,
                'wbs_id' => 13,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 04:42:15',
                'updated_at' => '2019-01-17 04:42:15',
            ),
            24 => 
            array (
                'id' => 25,
                'purchase_requisition_id' => 8,
                'quantity' => 2,
                'reserved' => 0,
                'material_id' => 16,
                'resource_id' => NULL,
                'wbs_id' => 14,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 04:42:15',
                'updated_at' => '2019-01-17 04:42:15',
            ),
            25 => 
            array (
                'id' => 26,
                'purchase_requisition_id' => 9,
                'quantity' => 3,
                'reserved' => 0,
                'material_id' => NULL,
                'resource_id' => 1,
                'wbs_id' => 12,
                'alocation' => NULL,
                'created_at' => '2019-01-17 04:42:47',
                'updated_at' => '2019-01-17 04:42:47',
            ),
            26 => 
            array (
                'id' => 27,
                'purchase_requisition_id' => 9,
                'quantity' => 5,
                'reserved' => 3,
                'material_id' => NULL,
                'resource_id' => 4,
                'wbs_id' => 13,
                'alocation' => NULL,
                'created_at' => '2019-01-17 04:42:47',
                'updated_at' => '2019-01-17 04:44:29',
            ),
            27 => 
            array (
                'id' => 28,
                'purchase_requisition_id' => 10,
                'quantity' => 12,
                'reserved' => 0,
                'material_id' => 4,
                'resource_id' => NULL,
                'wbs_id' => 5,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 06:51:04',
                'updated_at' => '2019-01-17 06:51:04',
            ),
            28 => 
            array (
                'id' => 29,
                'purchase_requisition_id' => 10,
                'quantity' => 5,
                'reserved' => 0,
                'material_id' => 13,
                'resource_id' => NULL,
                'wbs_id' => 4,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 06:51:04',
                'updated_at' => '2019-01-17 06:51:04',
            ),
            29 => 
            array (
                'id' => 30,
                'purchase_requisition_id' => 10,
                'quantity' => 15,
                'reserved' => 0,
                'material_id' => 28,
                'resource_id' => NULL,
                'wbs_id' => 6,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 06:51:04',
                'updated_at' => '2019-01-17 06:51:04',
            ),
            30 => 
            array (
                'id' => 31,
                'purchase_requisition_id' => 10,
                'quantity' => 5,
                'reserved' => 0,
                'material_id' => 32,
                'resource_id' => NULL,
                'wbs_id' => 6,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 06:51:04',
                'updated_at' => '2019-01-17 06:51:04',
            ),
            31 => 
            array (
                'id' => 32,
                'purchase_requisition_id' => 10,
                'quantity' => 8,
                'reserved' => 0,
                'material_id' => 38,
                'resource_id' => NULL,
                'wbs_id' => 7,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 06:51:04',
                'updated_at' => '2019-01-17 06:51:04',
            ),
            32 => 
            array (
                'id' => 33,
                'purchase_requisition_id' => 11,
                'quantity' => 5,
                'reserved' => 0,
                'material_id' => NULL,
                'resource_id' => 2,
                'wbs_id' => 5,
                'alocation' => NULL,
                'created_at' => '2019-01-17 06:52:06',
                'updated_at' => '2019-01-17 06:52:06',
            ),
            33 => 
            array (
                'id' => 34,
                'purchase_requisition_id' => 11,
                'quantity' => 5,
                'reserved' => 0,
                'material_id' => NULL,
                'resource_id' => 4,
                'wbs_id' => 6,
                'alocation' => NULL,
                'created_at' => '2019-01-17 06:52:06',
                'updated_at' => '2019-01-17 06:52:06',
            ),
            34 => 
            array (
                'id' => 35,
                'purchase_requisition_id' => 12,
                'quantity' => 15,
                'reserved' => 15,
                'material_id' => 36,
                'resource_id' => NULL,
                'wbs_id' => 5,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 06:53:05',
                'updated_at' => '2019-01-17 06:55:05',
            ),
            35 => 
            array (
                'id' => 36,
                'purchase_requisition_id' => 12,
                'quantity' => 12,
                'reserved' => 12,
                'material_id' => 30,
                'resource_id' => NULL,
                'wbs_id' => 6,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 06:53:05',
                'updated_at' => '2019-01-17 06:55:05',
            ),
            36 => 
            array (
                'id' => 37,
                'purchase_requisition_id' => 12,
                'quantity' => 5,
                'reserved' => 5,
                'material_id' => 33,
                'resource_id' => NULL,
                'wbs_id' => 4,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 06:53:05',
                'updated_at' => '2019-01-17 06:55:05',
            ),
            37 => 
            array (
                'id' => 38,
                'purchase_requisition_id' => 12,
                'quantity' => 2,
                'reserved' => 2,
                'material_id' => 43,
                'resource_id' => NULL,
                'wbs_id' => 7,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 06:53:05',
                'updated_at' => '2019-01-17 06:55:05',
            ),
            38 => 
            array (
                'id' => 39,
                'purchase_requisition_id' => 12,
                'quantity' => 5,
                'reserved' => 5,
                'material_id' => 38,
                'resource_id' => NULL,
                'wbs_id' => 6,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 06:53:05',
                'updated_at' => '2019-01-17 06:55:05',
            ),
            39 => 
            array (
                'id' => 40,
                'purchase_requisition_id' => 13,
                'quantity' => 4,
                'reserved' => 4,
                'material_id' => NULL,
                'resource_id' => 2,
                'wbs_id' => 4,
                'alocation' => NULL,
                'created_at' => '2019-01-17 06:53:57',
                'updated_at' => '2019-01-17 06:55:38',
            ),
            40 => 
            array (
                'id' => 41,
                'purchase_requisition_id' => 13,
                'quantity' => 3,
                'reserved' => 3,
                'material_id' => NULL,
                'resource_id' => 1,
                'wbs_id' => 6,
                'alocation' => NULL,
                'created_at' => '2019-01-17 06:53:57',
                'updated_at' => '2019-01-17 06:55:38',
            ),
            41 => 
            array (
                'id' => 42,
                'purchase_requisition_id' => 13,
                'quantity' => 2,
                'reserved' => 2,
                'material_id' => NULL,
                'resource_id' => 3,
                'wbs_id' => 7,
                'alocation' => NULL,
                'created_at' => '2019-01-17 06:53:57',
                'updated_at' => '2019-01-17 06:55:38',
            ),
            42 => 
            array (
                'id' => 43,
                'purchase_requisition_id' => 13,
                'quantity' => 3,
                'reserved' => 3,
                'material_id' => NULL,
                'resource_id' => 4,
                'wbs_id' => 7,
                'alocation' => NULL,
                'created_at' => '2019-01-17 06:53:57',
                'updated_at' => '2019-01-17 06:55:38',
            ),
            43 => 
            array (
                'id' => 44,
                'purchase_requisition_id' => 14,
                'quantity' => 15,
                'reserved' => 0,
                'material_id' => 5,
                'resource_id' => NULL,
                'wbs_id' => 12,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 06:58:29',
                'updated_at' => '2019-01-17 06:58:29',
            ),
            44 => 
            array (
                'id' => 45,
                'purchase_requisition_id' => 14,
                'quantity' => 4,
                'reserved' => 0,
                'material_id' => 31,
                'resource_id' => NULL,
                'wbs_id' => 13,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 06:58:30',
                'updated_at' => '2019-01-17 06:58:30',
            ),
            45 => 
            array (
                'id' => 46,
                'purchase_requisition_id' => 14,
                'quantity' => 8,
                'reserved' => 0,
                'material_id' => 42,
                'resource_id' => NULL,
                'wbs_id' => 14,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 06:58:30',
                'updated_at' => '2019-01-17 06:58:30',
            ),
            46 => 
            array (
                'id' => 47,
                'purchase_requisition_id' => 14,
                'quantity' => 12,
                'reserved' => 0,
                'material_id' => 30,
                'resource_id' => NULL,
                'wbs_id' => 12,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 06:58:30',
                'updated_at' => '2019-01-17 06:58:30',
            ),
            47 => 
            array (
                'id' => 48,
                'purchase_requisition_id' => 14,
                'quantity' => 18,
                'reserved' => 0,
                'material_id' => 33,
                'resource_id' => NULL,
                'wbs_id' => 12,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 06:58:30',
                'updated_at' => '2019-01-17 06:58:30',
            ),
            48 => 
            array (
                'id' => 49,
                'purchase_requisition_id' => 15,
                'quantity' => 3,
                'reserved' => 0,
                'material_id' => NULL,
                'resource_id' => 1,
                'wbs_id' => 12,
                'alocation' => NULL,
                'created_at' => '2019-01-17 06:59:14',
                'updated_at' => '2019-01-17 06:59:14',
            ),
            49 => 
            array (
                'id' => 50,
                'purchase_requisition_id' => 15,
                'quantity' => 5,
                'reserved' => 0,
                'material_id' => NULL,
                'resource_id' => 2,
                'wbs_id' => 12,
                'alocation' => NULL,
                'created_at' => '2019-01-17 06:59:14',
                'updated_at' => '2019-01-17 06:59:14',
            ),
            50 => 
            array (
                'id' => 51,
                'purchase_requisition_id' => 15,
                'quantity' => 3,
                'reserved' => 0,
                'material_id' => NULL,
                'resource_id' => 3,
                'wbs_id' => 13,
                'alocation' => NULL,
                'created_at' => '2019-01-17 06:59:14',
                'updated_at' => '2019-01-17 06:59:14',
            ),
            51 => 
            array (
                'id' => 52,
                'purchase_requisition_id' => 15,
                'quantity' => 5,
                'reserved' => 0,
                'material_id' => NULL,
                'resource_id' => 4,
                'wbs_id' => 14,
                'alocation' => NULL,
                'created_at' => '2019-01-17 06:59:14',
                'updated_at' => '2019-01-17 06:59:14',
            ),
            52 => 
            array (
                'id' => 53,
                'purchase_requisition_id' => 16,
                'quantity' => 5,
                'reserved' => 5,
                'material_id' => 32,
                'resource_id' => NULL,
                'wbs_id' => 13,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 07:00:13',
                'updated_at' => '2019-01-17 07:01:56',
            ),
            53 => 
            array (
                'id' => 54,
                'purchase_requisition_id' => 16,
                'quantity' => 15,
                'reserved' => 15,
                'material_id' => 68,
                'resource_id' => NULL,
                'wbs_id' => 12,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 07:00:13',
                'updated_at' => '2019-01-17 07:01:56',
            ),
            54 => 
            array (
                'id' => 55,
                'purchase_requisition_id' => 16,
                'quantity' => 12,
                'reserved' => 12,
                'material_id' => 41,
                'resource_id' => NULL,
                'wbs_id' => 15,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 07:00:13',
                'updated_at' => '2019-01-17 07:01:56',
            ),
            55 => 
            array (
                'id' => 56,
                'purchase_requisition_id' => 16,
                'quantity' => 8,
                'reserved' => 8,
                'material_id' => 3,
                'resource_id' => NULL,
                'wbs_id' => 12,
                'alocation' => 'Stock',
                'created_at' => '2019-01-17 07:00:13',
                'updated_at' => '2019-01-17 07:01:56',
            ),
            56 => 
            array (
                'id' => 57,
                'purchase_requisition_id' => 16,
                'quantity' => 10,
                'reserved' => 10,
                'material_id' => 17,
                'resource_id' => NULL,
                'wbs_id' => 13,
                'alocation' => 'Consumption',
                'created_at' => '2019-01-17 07:00:13',
                'updated_at' => '2019-01-17 07:01:56',
            ),
            57 => 
            array (
                'id' => 58,
                'purchase_requisition_id' => 17,
                'quantity' => 5,
                'reserved' => 5,
                'material_id' => NULL,
                'resource_id' => 2,
                'wbs_id' => 12,
                'alocation' => NULL,
                'created_at' => '2019-01-17 07:00:58',
                'updated_at' => '2019-01-17 07:02:17',
            ),
            58 => 
            array (
                'id' => 59,
                'purchase_requisition_id' => 17,
                'quantity' => 3,
                'reserved' => 3,
                'material_id' => NULL,
                'resource_id' => 3,
                'wbs_id' => 13,
                'alocation' => NULL,
                'created_at' => '2019-01-17 07:00:58',
                'updated_at' => '2019-01-17 07:02:17',
            ),
            59 => 
            array (
                'id' => 60,
                'purchase_requisition_id' => 17,
                'quantity' => 5,
                'reserved' => 5,
                'material_id' => NULL,
                'resource_id' => 4,
                'wbs_id' => 12,
                'alocation' => NULL,
                'created_at' => '2019-01-17 07:00:59',
                'updated_at' => '2019-01-17 07:02:17',
            ),
            60 => 
            array (
                'id' => 61,
                'purchase_requisition_id' => 17,
                'quantity' => 3,
                'reserved' => 3,
                'material_id' => NULL,
                'resource_id' => 1,
                'wbs_id' => 15,
                'alocation' => NULL,
                'created_at' => '2019-01-17 07:00:59',
                'updated_at' => '2019-01-17 07:02:17',
            ),
        ));
        
        
    }
}